'use client';
import { useEffect, useState } from 'react';
type Contact = {id:string;slug:string;business_name:string;status:string;routing_email:string;quote_routing_enabled:boolean;quote_routing_basis:string;public_email:string;public_email_approved:boolean;public_email_approved_at:string|null};
export default function ContactsPage() {
  const [query,setQuery]=useState(''),[contact,setContact]=useState<Contact|null>(null),[note,setNote]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  useEffect(() => { const initial = new URLSearchParams(window.location.search).get('shop'); if (initial) setQuery(initial); }, []);
  async function lookup(e:React.FormEvent) { e.preventDefault();setBusy(true);setMessage('');setContact(null);try{const response=await fetch('/api/admin/installer-contact?shop='+encodeURIComponent(query),{cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error);setContact({...data,id:String(data.id),routing_email:data.routing_email||'',public_email:data.public_email||''});setNote('');}catch(error){setMessage(error instanceof Error?error.message:'Lookup failed.');}finally{setBusy(false);} }
  async function save(e:React.FormEvent) {e.preventDefault();if(!contact)return;setBusy(true);setMessage('');try{const response=await fetch('/api/admin/installer-contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...contact,note})});const data=await response.json();if(!response.ok)throw new Error(data.error);setContact({...data,id:String(data.id),routing_email:data.routing_email||'',public_email:data.public_email||''});setMessage('Contact permissions saved. The public profile and quote eligibility now use these settings.');}catch(error){setMessage(error instanceof Error?error.message:'Could not save. Reload before retrying.');}finally{setBusy(false);} }
  return <div className="max-w-2xl space-y-6"><h1 className="text-2xl font-bold">Shop contact permissions</h1><p className="text-gray-600">Private routing and public email publication are separate. Existing-routing status records the previous delivery channel; it does not claim newly obtained shop consent.</p><form onSubmit={lookup} className="flex items-end gap-3"><div className="flex-1"><label htmlFor="contact-lookup" className="block text-sm mb-1">Shop ID or profile slug</label><input id="contact-lookup" required maxLength={180} className="input-field w-full" value={query} onChange={e=>setQuery(e.target.value)}/></div><button disabled={busy} className="btn-primary">Find shop</button></form>{message&&<p role="status" className="rounded-lg border p-3">{message}</p>}{contact&&<form onSubmit={save} className="card p-5 space-y-5"><h2 className="text-xl font-semibold">{contact.business_name}</h2><p className="text-sm">Status: {contact.status} · Routing basis: {contact.quote_routing_basis||'Not reviewed'}</p><div><label htmlFor="routing-email" className="block text-sm mb-1">Private routing email</label><input id="routing-email" type="email" maxLength={255} className="input-field w-full" value={contact.routing_email} onChange={e=>setContact({...contact,routing_email:e.target.value})}/></div><label className="flex gap-3 items-start"><input type="checkbox" className="mt-1" checked={contact.quote_routing_enabled} onChange={e=>setContact({...contact,quote_routing_enabled:e.target.checked})}/><span>Enable installation requests to this private address. Confirm the shop’s participation and record the evidence below.</span></label><div><label htmlFor="public-email" className="block text-sm mb-1">Public business email (optional)</label><input id="public-email" type="email" maxLength={255} className="input-field w-full" value={contact.public_email} onChange={e=>setContact({...contact,public_email:e.target.value})}/></div><label className="flex gap-3 items-start"><input type="checkbox" className="mt-1" checked={contact.public_email_approved} onChange={e=>setContact({...contact,public_email_approved:e.target.checked})}/><span>The shop has explicitly approved publishing this business email on its public profile.</span></label><div><label htmlFor="contact-note" className="block text-sm mb-1">Permission or change record *</label><textarea id="contact-note" required minLength={10} maxLength={500} className="input-field w-full" value={note} onChange={e=>setNote(e.target.value)} placeholder="Record who requested/approved the change, when, and the supporting reference."/></div><button disabled={busy} className="btn-primary">{busy?'Saving…':'Save contact permissions'}</button><a href={'/installer/'+contact.slug} className="text-vicrez-red underline ml-4">View public profile</a></form>}</div>;
}
