// State-specific data for tire shop startup guides.
// Sources: state SOS websites, EPA waste tire program directories,
// state revenue/sales tax departments (verified June 2026).
// Numbers are rounded for usability; always verify current rates with state authorities before filing.

export interface StateData {
  slug: string;
  abbr: string;
  name: string;
  capital: string;
  registeredVehicles: string; // millions, formatted
  topMetros: string[];
  costTier: 'low' | 'mid' | 'high';
  costMultiplier: number; // applied to national-average startup cost
  // Licensing
  llcFilingFee: string;
  llcFilingTimeDays: string;
  salesTaxRate: string; // state base rate (local adds on top)
  needsStateBusinessLicense: boolean;
  // Industry-specific
  needsAutomotiveRepairLicense: boolean;
  automotiveRepairAgency?: string;
  epaWasteTireProgram: boolean;
  epaProgramName?: string;
  epaTireDisposalFee?: string;
  // Market notes
  startupCostRange: { mobile: string; singleBay: string; multiBay: string };
  marketNotes: string;
  whyHere: string[]; // 3 reasons this state is a good (or interesting) tire shop market
  watchouts: string[]; // 2-3 state-specific watchouts
  // Resources
  sosUrl: string;
  taxUrl: string;
  epaUrl?: string;
  repairLicenseUrl?: string;
}

export const STATE_DATA: Record<string, StateData> = {
  texas: {
    slug: 'texas',
    abbr: 'TX',
    name: 'Texas',
    capital: 'Austin',
    registeredVehicles: '23.8M',
    topMetros: ['Houston', 'Dallas–Fort Worth', 'San Antonio', 'Austin', 'El Paso'],
    costTier: 'mid',
    costMultiplier: 1.0,
    llcFilingFee: '$300',
    llcFilingTimeDays: '2–5 business days online',
    salesTaxRate: '6.25% state + up to 2% local (max 8.25%)',
    needsStateBusinessLicense: false,
    needsAutomotiveRepairLicense: false,
    epaWasteTireProgram: true,
    epaProgramName: 'TCEQ Used or Scrap Tire Program',
    epaTireDisposalFee: '$2 per tire (collected from customer at sale)',
    startupCostRange: {
      mobile: '$35K–$80K',
      singleBay: '$92K–$210K',
      multiBay: '$195K–$405K',
    },
    marketNotes:
      'Texas is one of the most favorable tire shop markets in the U.S. — no state income tax, no state business license requirement, and a vehicle population per capita that is 35% higher than the national average. Houston and Dallas–Fort Worth alone account for more than 11M registered vehicles. Commercial fleet density (oil and gas, construction, last-mile delivery) is among the highest in the country.',
    whyHere: [
      'No state income tax keeps owner take-home 5–9 percentage points higher than coastal states.',
      'Per-capita vehicle ownership 35% above national average — strong tire replacement demand.',
      'Massive commercial fleet base (energy, construction, logistics) supports recurring revenue.',
    ],
    watchouts: [
      'Summer heat (Houston, San Antonio) accelerates tire wear and creates seasonal demand spikes — staff for it or you will lose customers to wait times.',
      'TCEQ waste tire compliance is enforced — you must use a registered transporter and keep manifests for 3 years.',
      'Commercial property is appreciating fast in Austin and DFW. Lock in long leases or buy if you can.',
    ],
    sosUrl: 'https://www.sos.state.tx.us/corp/sosda/index.shtml',
    taxUrl: 'https://comptroller.texas.gov/taxes/sales/',
    epaUrl: 'https://www.tceq.texas.gov/permitting/waste_permits/ihw_permits/usedscraptires',
  },
  california: {
    slug: 'california',
    abbr: 'CA',
    name: 'California',
    capital: 'Sacramento',
    registeredVehicles: '31.4M',
    topMetros: ['Los Angeles', 'San Francisco Bay Area', 'San Diego', 'Sacramento', 'Riverside–San Bernardino'],
    costTier: 'high',
    costMultiplier: 1.25,
    llcFilingFee: '$70 + $800 annual franchise tax',
    llcFilingTimeDays: '5–10 business days standard',
    salesTaxRate: '7.25% state + 1.0–2.5% local (range 7.25–10.75%)',
    needsStateBusinessLicense: true,
    needsAutomotiveRepairLicense: true,
    automotiveRepairAgency: 'Bureau of Automotive Repair (BAR)',
    epaWasteTireProgram: true,
    epaProgramName: 'CalRecycle Waste Tire Program',
    epaTireDisposalFee: '$1.75 per tire (state) + retailer-set transport fee',
    startupCostRange: {
      mobile: '$45K–$105K',
      singleBay: '$118K–$275K',
      multiBay: '$250K–$525K',
    },
    marketNotes:
      'California is a high-cost but high-revenue market. Average ticket runs 25–35% above national average due to higher labor costs and premium tire preference, but rent, payroll, insurance, and compliance costs are all in the top quartile nationally. BAR registration is non-negotiable and adds consumer-protection rules that take real attention.',
    whyHere: [
      '31M+ registered vehicles — largest single-state market in the U.S.',
      'Premium-tire preference is highest in the country, meaning higher dollar margins per service.',
      'Strong EV adoption is creating demand for EV-specific tire expertise (heavier vehicles, faster wear).',
    ],
    watchouts: [
      'BAR (Bureau of Automotive Repair) registration is required. Comes with consumer-protection disclosure rules; non-compliance fines start at $1,000 per violation.',
      '$800/year LLC franchise tax is owed regardless of revenue — budget for it from day one.',
      'CalRecycle compliance and waste tire manifesting are audited more aggressively than most states.',
    ],
    sosUrl: 'https://www.sos.ca.gov/business-programs/business-entities',
    taxUrl: 'https://www.cdtfa.ca.gov/taxes-and-fees/sales-use-tax.htm',
    epaUrl: 'https://calrecycle.ca.gov/Tires/',
    repairLicenseUrl: 'https://www.bar.ca.gov/Industry/Auto_Repair_Dealer.html',
  },
  florida: {
    slug: 'florida',
    abbr: 'FL',
    name: 'Florida',
    capital: 'Tallahassee',
    registeredVehicles: '17.9M',
    topMetros: ['Miami–Fort Lauderdale', 'Tampa Bay', 'Orlando', 'Jacksonville', 'Cape Coral–Fort Myers'],
    costTier: 'mid',
    costMultiplier: 1.0,
    llcFilingFee: '$125',
    llcFilingTimeDays: '2–7 business days online',
    salesTaxRate: '6.0% state + 0.5–1.5% local (range 6.0–7.5%)',
    needsStateBusinessLicense: false,
    needsAutomotiveRepairLicense: true,
    automotiveRepairAgency: 'Florida Department of Agriculture and Consumer Services (Motor Vehicle Repair Registration)',
    epaWasteTireProgram: true,
    epaProgramName: 'FDEP Waste Tire Program',
    epaTireDisposalFee: '$1 per new tire sold (state) + retailer transport pass-through',
    startupCostRange: {
      mobile: '$36K–$82K',
      singleBay: '$96K–$215K',
      multiBay: '$205K–$410K',
    },
    marketNotes:
      'Florida combines strong fundamentals — no state income tax, fast-growing population, year-round driving — with relatively low entry costs. The Motor Vehicle Repair Registration through FDACS is straightforward but mandatory; do not skip it. Insurance costs run 15–25% above national average due to weather, fraud, and auto-litigation environment.',
    whyHere: [
      'No state income tax preserves owner profit.',
      'Population growth is among the fastest in the U.S. — vehicle base is expanding.',
      'Year-round driving climate means no seasonal demand collapse.',
    ],
    watchouts: [
      'Motor Vehicle Repair Registration (FDACS) is required before you take a single paying customer. $50–$300 fee depending on number of employees.',
      'Hurricane prep is real. Brick-and-mortar shops should budget for $5K–$15K in shutters / generator / storm prep, and an additional 1–2 weeks of working capital reserve.',
      'General liability insurance premiums in Florida run 20–40% above the national average.',
    ],
    sosUrl: 'https://dos.fl.gov/sunbiz/start-business/',
    taxUrl: 'https://floridarevenue.com/taxes/taxesfees/Pages/sales_tax.aspx',
    epaUrl: 'https://floridadep.gov/waste/waste-reduction/content/waste-tires',
    repairLicenseUrl: 'https://www.fdacs.gov/Business-Services/Motor-Vehicle-Repair',
  },
  'new-york': {
    slug: 'new-york',
    abbr: 'NY',
    name: 'New York',
    capital: 'Albany',
    registeredVehicles: '11.4M',
    topMetros: ['New York City', 'Buffalo', 'Rochester', 'Syracuse', 'Albany'],
    costTier: 'high',
    costMultiplier: 1.25,
    llcFilingFee: '$200 + $9 biennial fee + publication requirement (varies $200–$2,000+)',
    llcFilingTimeDays: '5–15 business days; faster with expedite fee',
    salesTaxRate: '4.0% state + 3.0–4.875% local (range 7.0–8.875%)',
    needsStateBusinessLicense: false,
    needsAutomotiveRepairLicense: true,
    automotiveRepairAgency: 'NYS DMV Motor Vehicle Repair Shop Registration',
    epaWasteTireProgram: true,
    epaProgramName: 'NYSDEC Waste Tire Management Program',
    epaTireDisposalFee: '$2.50 per new tire sold (state surcharge)',
    startupCostRange: {
      mobile: '$48K–$108K',
      singleBay: '$120K–$280K',
      multiBay: '$255K–$535K',
    },
    marketNotes:
      'New York has unique challenges — LLC publication requirement adds $200–$2,000+ to startup, NYC commercial rent is among the highest in the country, and NYSDMV repair shop registration adds consumer-protection rules. But Buffalo, Rochester, and Syracuse all have meaningful upstate markets with much lower entry costs than NYC. Mobile tire businesses in NYC outer boroughs (Queens, Brooklyn, Bronx) are particularly underserved.',
    whyHere: [
      '11M+ registered vehicles concentrated in dense, drivable suburban/exurban rings.',
      'Mobile tire is wide open in NYC outer boroughs and Long Island — parking and convenience make shop visits painful.',
      'Upstate metros (Buffalo, Rochester) have entry costs 25–40% below downstate with stable demand.',
    ],
    watchouts: [
      'LLC publication requirement is real and varies wildly by county. Cheapest counties (Albany, Onondaga) cost $200–$400; NYC counties (NY, Kings, Queens) cost $1,200–$2,500+.',
      'NYSDMV Motor Vehicle Repair Shop registration is required and renews annually. Budget time for the inspection process.',
      'NYC parking and commercial loading restrictions can make mobile operations operationally complex. Scout your service area.',
    ],
    sosUrl: 'https://dos.ny.gov/forming-limited-liability-company',
    taxUrl: 'https://www.tax.ny.gov/bus/st/stidx.htm',
    epaUrl: 'https://www.dec.ny.gov/chemical/8512.html',
    repairLicenseUrl: 'https://dmv.ny.gov/registration/registering-repair-shop',
  },
  ohio: {
    slug: 'ohio',
    abbr: 'OH',
    name: 'Ohio',
    capital: 'Columbus',
    registeredVehicles: '11.9M',
    topMetros: ['Columbus', 'Cleveland', 'Cincinnati', 'Toledo', 'Akron'],
    costTier: 'mid',
    costMultiplier: 1.0,
    llcFilingFee: '$99',
    llcFilingTimeDays: '3–7 business days online',
    salesTaxRate: '5.75% state + 0.75–2.25% local (range 6.5–8.0%)',
    needsStateBusinessLicense: false,
    needsAutomotiveRepairLicense: false,
    epaWasteTireProgram: true,
    epaProgramName: 'Ohio EPA Scrap Tire Management Program',
    epaTireDisposalFee: '$1 per new tire (state recycling fee)',
    startupCostRange: {
      mobile: '$34K–$78K',
      singleBay: '$90K–$205K',
      multiBay: '$190K–$395K',
    },
    marketNotes:
      'Ohio offers one of the best risk-adjusted markets in the country — low LLC and licensing costs, no state-level automotive repair license, moderate sales tax, and a strong manufacturing and logistics fleet base. Columbus is the fastest-growing metro and Cleveland has a deep commercial fleet ecosystem (Sherwin-Williams, Goodyear, Progressive — many fleet contractors). Winter tire seasonal demand creates a clean revenue pattern.',
    whyHere: [
      'Low cost of entry — among the cheapest LLC filing fees and no state-level repair license.',
      'Strong winter tire seasonal demand (Oct–Dec) creates predictable revenue spikes.',
      'Columbus metro is one of the fastest-growing in the U.S. — vehicle base is expanding 2.5%+ per year.',
    ],
    watchouts: [
      'Winter logistics: salt and slush damage equipment and consumables faster than southern states. Budget 10–15% higher maintenance.',
      'Cleveland and Cincinnati have entrenched independent shop networks — differentiate clearly or focus on underserved suburbs.',
      'Ohio EPA scrap tire compliance is enforced; use registered transporters and keep manifests.',
    ],
    sosUrl: 'https://www.ohiosos.gov/businesses/',
    taxUrl: 'https://tax.ohio.gov/business/ohio-business-taxes/sales-and-use',
    epaUrl: 'https://epa.ohio.gov/divisions-and-offices/materials-and-waste-management/scrap-tires',
  },
  alabama: {
    slug: 'alabama',
    abbr: 'AL',
    name: 'Alabama',
    capital: 'Montgomery',
    registeredVehicles: '4.4M',
    topMetros: ['Birmingham', 'Huntsville', 'Mobile', 'Montgomery', 'Tuscaloosa'],
    costTier: 'low',
    costMultiplier: 0.85,
    llcFilingFee: '$200 (Certificate of Formation) + $25 name reservation',
    llcFilingTimeDays: '3–7 business days online',
    salesTaxRate: '4.0% state + 1.0–7.5% local (range 5.0–11.5%)',
    needsStateBusinessLicense: false,
    needsAutomotiveRepairLicense: false,
    epaWasteTireProgram: true,
    epaProgramName: 'ADEM Scrap Tire Program',
    epaTireDisposalFee: '$1 per new tire sold (state environmental fee)',
    startupCostRange: {
      mobile: '$30K–$72K',
      singleBay: '$81K–$187K',
      multiBay: '$170K–$357K',
    },
    marketNotes:
      'Alabama offers one of the cheapest entry markets in the Southeast. Birmingham and Huntsville (rapidly growing thanks to aerospace and defense contracting) have strong fleet demand, and labor costs run 20–25% below national average. Total local sales tax can exceed 11% in some jurisdictions — pricing must account for it.',
    whyHere: [
      'Labor and rent 20–25% below national average — fastest path to positive cash flow.',
      'Huntsville aerospace/defense corridor is driving fleet and contractor vehicle growth.',
      'No state automotive repair license — only local business licensing required.',
    ],
    watchouts: [
      'Local sales tax stacking can push combined rate above 11% in Birmingham, Montgomery, and parts of Mobile County. Print pricing carefully.',
      'Rural counties have very thin labor pools for certified techs — recruit early and offer training.',
      'Heat and humidity accelerate inventory degradation; climate-control storage is worth the spend.',
    ],
    sosUrl: 'https://www.sos.alabama.gov/business-entities',
    taxUrl: 'https://www.revenue.alabama.gov/sales-use/',
    epaUrl: 'https://adem.alabama.gov/programs/land/scraptires.cnt',
  },
  alaska: {
    slug: 'alaska',
    abbr: 'AK',
    name: 'Alaska',
    capital: 'Juneau',
    registeredVehicles: '0.78M',
    topMetros: ['Anchorage', 'Fairbanks', 'Juneau', 'Wasilla'],
    costTier: 'high',
    costMultiplier: 1.25,
    llcFilingFee: '$250 + $100 biennial report',
    llcFilingTimeDays: '10–15 business days (mail or online)',
    salesTaxRate: 'No state sales tax; local sales tax 0–7.5% (varies by borough)',
    needsStateBusinessLicense: true,
    needsAutomotiveRepairLicense: false,
    epaWasteTireProgram: false,
    startupCostRange: {
      mobile: '$45K–$105K',
      singleBay: '$118K–$275K',
      multiBay: '$250K–$525K',
    },
    marketNotes:
      'Alaska is small in absolute terms but unique. Winter tire demand is nearly universal — studded and dedicated winter tires are standard. Anchorage and Fairbanks account for the majority of registered vehicles. Logistics costs are the dominant variable: inventory must be barged or trucked in, and a single multi-bay shop can dominate a regional market with little competition.',
    whyHere: [
      'Universal winter tire demand creates a guaranteed seasonal revenue spike.',
      'No state sales tax (most boroughs); some boroughs add local sales tax.',
      'Low competition outside Anchorage — single shops can capture entire regional markets.',
    ],
    watchouts: [
      'Inventory logistics are brutal. Lead times of 4–8 weeks and 25–40% freight markups are normal — order well ahead of the September–October peak.',
      'Alaska Business License ($50/year) is required for every business at the state level.',
      'No state EPA waste tire program — disposal is handled by local boroughs; verify before signing a lease.',
    ],
    sosUrl: 'https://www.commerce.alaska.gov/web/cbpl/Corporations.aspx',
    taxUrl: 'https://tax.alaska.gov/programs/programs/index.aspx?60610',
  },
  arizona: {
    slug: 'arizona',
    abbr: 'AZ',
    name: 'Arizona',
    capital: 'Phoenix',
    registeredVehicles: '6.4M',
    topMetros: ['Phoenix', 'Tucson', 'Mesa', 'Chandler', 'Scottsdale'],
    costTier: 'mid',
    costMultiplier: 1.0,
    llcFilingFee: '$50 (online) + publication requirement in some counties',
    llcFilingTimeDays: '14–20 business days standard; 7 days with expedite ($35)',
    salesTaxRate: '5.6% state + 0.7–5.6% local TPT (range 6.3–11.2%)',
    needsStateBusinessLicense: false,
    needsAutomotiveRepairLicense: false,
    epaWasteTireProgram: true,
    epaProgramName: 'ADEQ Waste Tire Program',
    epaTireDisposalFee: '$2 per new tire sold (state recycling fee)',
    startupCostRange: {
      mobile: '$35K–$85K',
      singleBay: '$95K–$220K',
      multiBay: '$200K–$420K',
    },
    marketNotes:
      'Arizona\'s tire market is shaped by heat. Phoenix temperatures routinely exceed 110°F in summer, dramatically accelerating tread and sidewall wear — tire replacement intervals are 25–35% shorter than national average. Phoenix metro is one of the fastest-growing in the country and is now larger than Boston or DC by registered vehicle count.',
    whyHere: [
      'Extreme heat shortens tire life — replacement intervals 25–35% shorter than national average.',
      'Phoenix metro is one of the fastest-growing in the U.S.; vehicle base growing 2–3% per year.',
      'TPT (Transaction Privilege Tax) is collected from the business, not the customer — pricing can be cleaner if structured well.',
    ],
    watchouts: [
      'Maricopa and Pima counties no longer require LLC publication, but smaller counties still do — verify before filing.',
      'TPT (Arizona\'s version of sales tax) has city-specific rates layered on top — Phoenix, Mesa, Tucson all differ. Use ADOR\'s rate lookup, not generic tax software.',
      'Summer heat makes outdoor and mobile work physically punishing. Plan for early-morning shifts and hydration policies.',
    ],
    sosUrl: 'https://azcc.gov/corporations',
    taxUrl: 'https://azdor.gov/transaction-privilege-tax-tpt',
    epaUrl: 'https://azdeq.gov/waste-tires',
  },
  arkansas: {
    slug: 'arkansas',
    abbr: 'AR',
    name: 'Arkansas',
    capital: 'Little Rock',
    registeredVehicles: '2.6M',
    topMetros: ['Little Rock', 'Fayetteville–Springdale', 'Fort Smith', 'Jonesboro'],
    costTier: 'low',
    costMultiplier: 0.85,
    llcFilingFee: '$45 (online) / $50 (paper)',
    llcFilingTimeDays: '2–5 business days online',
    salesTaxRate: '6.5% state + 0.125–5.125% local (range 6.625–11.625%)',
    needsStateBusinessLicense: false,
    needsAutomotiveRepairLicense: false,
    epaWasteTireProgram: true,
    epaProgramName: 'ADEQ Used Tire Recycling Program',
    epaTireDisposalFee: '$3 per new tire sold (rim-removal fee)',
    startupCostRange: {
      mobile: '$30K–$72K',
      singleBay: '$81K–$187K',
      multiBay: '$170K–$357K',
    },
    marketNotes:
      'Arkansas combines low entry costs with a meaningful trucking-corridor economy (I-40, I-30, I-55). Northwest Arkansas (Bentonville–Fayetteville–Springdale) is one of the fastest-growing metros in the country thanks to Walmart HQ, Tyson, and J.B. Hunt. Statewide labor and rent costs are well below national average.',
    whyHere: [
      '$45 LLC filing fee — among the cheapest in the U.S.',
      'Northwest Arkansas is one of the fastest-growing metros; vehicle base expanding rapidly.',
      'Strong trucking and logistics fleet base supports commercial recurring revenue.',
    ],
    watchouts: [
      '$3 per-tire rim-removal fee is higher than most states — disclose to customers clearly.',
      'Rural eastern Arkansas labor pool is thin; recruit ahead of opening.',
      'Tornado-belt weather increases insurance premiums — get quotes early.',
    ],
    sosUrl: 'https://www.sos.arkansas.gov/business-commercial-services-bcs',
    taxUrl: 'https://www.dfa.arkansas.gov/excise-tax/sales-and-use-tax/',
    epaUrl: 'https://www.adeq.state.ar.us/land/branch_recycling/used_tire/',
  },
  colorado: {
    slug: 'colorado',
    abbr: 'CO',
    name: 'Colorado',
    capital: 'Denver',
    registeredVehicles: '5.4M',
    topMetros: ['Denver', 'Colorado Springs', 'Aurora', 'Fort Collins', 'Lakewood'],
    costTier: 'mid',
    costMultiplier: 1.0,
    llcFilingFee: '$50 (online only)',
    llcFilingTimeDays: '1–3 business days online',
    salesTaxRate: '2.9% state + 0–8.3% local (range 2.9–11.2%)',
    needsStateBusinessLicense: false,
    needsAutomotiveRepairLicense: false,
    epaWasteTireProgram: true,
    epaProgramName: 'CDPHE Waste Tire Program',
    epaTireDisposalFee: '$0.55 per new tire sold (Waste Tire Administration Fee)',
    startupCostRange: {
      mobile: '$35K–$85K',
      singleBay: '$95K–$220K',
      multiBay: '$200K–$420K',
    },
    marketNotes:
      'Colorado is a strong dual-season tire market. Mandatory traction laws on I-70 and other mountain corridors drive winter and all-season demand, and Denver/Front Range population growth has been steady. Sales tax is unusually complex — Colorado is one of a handful of "home rule" states where local jurisdictions administer their own tax separately from the state.',
    whyHere: [
      'Mountain traction laws (I-70 chain/snow tire requirements) drive winter tire demand statewide.',
      'Denver metro is one of the strongest growth corridors west of the Mississippi.',
      '$50 LLC filing fee and 1–3 day turnaround make formation among the fastest in the U.S.',
    ],
    watchouts: [
      'Home-rule cities (Denver, Boulder, Colorado Springs, Aurora) administer sales tax separately — you may need multiple registrations and filings.',
      'Mountain shops have brutal winter logistics; plowing, heat, and 4WD service vehicles add 10–15% to OPEX.',
      'Front Range commercial rents have risen sharply post-2020 — lock in leases or buy where possible.',
    ],
    sosUrl: 'https://www.coloradosos.gov/biz/',
    taxUrl: 'https://tax.colorado.gov/sales-use-tax',
    epaUrl: 'https://cdphe.colorado.gov/hm/waste-tires',
  },
  connecticut: {
    slug: 'connecticut',
    abbr: 'CT',
    name: 'Connecticut',
    capital: 'Hartford',
    registeredVehicles: '2.9M',
    topMetros: ['Hartford', 'New Haven', 'Bridgeport', 'Stamford', 'Waterbury'],
    costTier: 'high',
    costMultiplier: 1.25,
    llcFilingFee: '$120',
    llcFilingTimeDays: '3–7 business days online',
    salesTaxRate: '6.35% state (no local add-on)',
    needsStateBusinessLicense: false,
    needsAutomotiveRepairLicense: true,
    automotiveRepairAgency: 'CT DMV Motor Vehicle Repair License (Limited or General Repairer)',
    epaWasteTireProgram: true,
    epaProgramName: 'CT DEEP Waste Tire Management',
    epaTireDisposalFee: 'Set by retailer; no state per-tire fee',
    startupCostRange: {
      mobile: '$45K–$105K',
      singleBay: '$118K–$275K',
      multiBay: '$250K–$525K',
    },
    marketNotes:
      'Connecticut has a relatively small but high-income vehicle base — Fairfield County alone has some of the highest household incomes in the country and disproportionate premium-tire demand. CT DMV requires a Motor Vehicle Repairer license (Limited Repairer is the typical tire-only classification), and inspection of the proposed location is part of the process.',
    whyHere: [
      'Fairfield County household incomes drive premium-tire and run-flat demand.',
      'Flat 6.35% sales tax (no local add-ons) simplifies pricing and POS configuration.',
      'Aging vehicle base in Hartford/New Haven/Bridgeport supports steady replacement demand.',
    ],
    watchouts: [
      'CT DMV Motor Vehicle Repairer license includes a physical site inspection — budget 30–60 days into your opening timeline.',
      'Commercial rent in lower Fairfield County is among the highest in the country — upstate Hartford metro is the cost-effective alternative.',
      'Winter salt damage shortens lift, compressor, and consumable life by 15–20%.',
    ],
    sosUrl: 'https://business.ct.gov/Start-a-Business',
    taxUrl: 'https://portal.ct.gov/DRS/Sales-Tax/Sales-and-Use-Tax-Information',
    epaUrl: 'https://portal.ct.gov/DEEP/Reduce-Reuse-Recycle/Waste-Tires',
    repairLicenseUrl: 'https://portal.ct.gov/DMV/Dealers-and-Repairers/Dealers-and-Repairers',
  },
  delaware: {
    slug: 'delaware',
    abbr: 'DE',
    name: 'Delaware',
    capital: 'Dover',
    registeredVehicles: '0.95M',
    topMetros: ['Wilmington', 'Dover', 'Newark'],
    costTier: 'mid',
    costMultiplier: 1.0,
    llcFilingFee: '$110 + $300 annual franchise tax',
    llcFilingTimeDays: '2–5 business days online',
    salesTaxRate: 'No state sales tax (gross receipts tax applies to businesses)',
    needsStateBusinessLicense: true,
    needsAutomotiveRepairLicense: false,
    epaWasteTireProgram: true,
    epaProgramName: 'DNREC Used Tire Management',
    epaTireDisposalFee: 'Set by retailer; no per-tire state fee',
    startupCostRange: {
      mobile: '$35K–$85K',
      singleBay: '$95K–$220K',
      multiBay: '$200K–$420K',
    },
    marketNotes:
      'Delaware is small but tax-favorable on the retail side — no sales tax means cleaner customer pricing. However, the state imposes a gross receipts tax on most businesses (roughly 0.4% for automotive services) plus a $300 annual LLC franchise tax. Wilmington and the I-95 corridor have meaningful commuter and fleet density.',
    whyHere: [
      'No state sales tax — customer-facing pricing is simpler and feels cheaper.',
      'I-95 corridor and Wilmington fleet base support steady commercial demand.',
      'Small geographic footprint means a single shop can serve a large share of the state.',
    ],
    watchouts: [
      'Gross receipts tax (~0.4% for automotive services) is owed on revenue, not profit — model it before opening.',
      '$300 annual LLC franchise tax is mandatory regardless of revenue.',
      'State Business License is required for all businesses; renews annually.',
    ],
    sosUrl: 'https://corp.delaware.gov/howtoform/',
    taxUrl: 'https://revenue.delaware.gov/business-tax/',
    epaUrl: 'https://dnrec.delaware.gov/waste-hazardous/solid/scrap-tires/',
  },
  georgia: {
    slug: 'georgia',
    abbr: 'GA',
    name: 'Georgia',
    capital: 'Atlanta',
    registeredVehicles: '8.6M',
    topMetros: ['Atlanta', 'Augusta', 'Savannah', 'Athens', 'Columbus'],
    costTier: 'mid',
    costMultiplier: 1.0,
    llcFilingFee: '$100 (online) / $110 (paper) + $50 annual registration',
    llcFilingTimeDays: '5–7 business days online',
    salesTaxRate: '4.0% state + 2–5% local (range 6.0–9.0%)',
    needsStateBusinessLicense: false,
    needsAutomotiveRepairLicense: false,
    epaWasteTireProgram: true,
    epaProgramName: 'Georgia EPD Scrap Tire Management Program',
    epaTireDisposalFee: '$1 per new tire sold (state)',
    startupCostRange: {
      mobile: '$35K–$85K',
      singleBay: '$95K–$220K',
      multiBay: '$200K–$420K',
    },
    marketNotes:
      'Georgia is one of the most attractive markets in the Southeast. Metro Atlanta\'s 6M+ population and concentration of distribution and logistics (Hartsfield-Jackson, UPS, Delta hubs) generate massive fleet demand. Savannah\'s port growth has driven trucking volume up consistently. No state-level repair license keeps friction low.',
    whyHere: [
      'Metro Atlanta logistics, distribution, and air-cargo industries generate enormous commercial fleet demand.',
      'Savannah port growth is driving trucking and intermodal vehicle volume.',
      'No state automotive repair license — only local business licenses required.',
    ],
    watchouts: [
      'Atlanta traffic and sprawl make site selection critical — proximity to ring-road exits matters more than CBD location.',
      'Hot, humid summers shorten tire life but also accelerate inventory degradation in non-climate-controlled storage.',
      'Atlanta commercial rents have risen 30%+ since 2020; secondary metros (Augusta, Columbus) offer better unit economics.',
    ],
    sosUrl: 'https://sos.ga.gov/georgia-corporations-division',
    taxUrl: 'https://dor.georgia.gov/taxes/business-taxes/sales-use-tax',
    epaUrl: 'https://epd.georgia.gov/land-protection-branch/scrap-tire-management-program',
  },
  hawaii: {
    slug: 'hawaii',
    abbr: 'HI',
    name: 'Hawaii',
    capital: 'Honolulu',
    registeredVehicles: '1.1M',
    topMetros: ['Honolulu', 'Hilo', 'Kailua-Kona', 'Kahului'],
    costTier: 'high',
    costMultiplier: 1.25,
    llcFilingFee: '$50 + $15 annual report',
    llcFilingTimeDays: '3–5 business days online',
    salesTaxRate: '4.0% General Excise Tax (GET) + 0.5% county surcharge on Oahu/Kauai/Hawaii (4.0–4.5% effective)',
    needsStateBusinessLicense: true,
    needsAutomotiveRepairLicense: false,
    epaWasteTireProgram: false,
    startupCostRange: {
      mobile: '$45K–$105K',
      singleBay: '$118K–$275K',
      multiBay: '$250K–$525K',
    },
    marketNotes:
      'Hawaii is a high-cost, logistics-constrained market. All tire inventory is shipped in by container, adding 20–35% to landed cost. Honolulu has the bulk of registered vehicles and the most competition. Outer islands have less competition but smaller demand pools. GET applies to the gross revenue of the business (not just retail sales).',
    whyHere: [
      'Salt-air corrosion and high heat shorten tire and component life — replacement intervals are below national average.',
      'Tourism rental-fleet rotation creates steady commercial demand.',
      'Outer islands (Big Island, Maui, Kauai) have less competition for a determined operator.',
    ],
    watchouts: [
      'Container shipping adds 20–35% to landed inventory cost; lead times of 3–6 weeks are normal.',
      'GET applies to gross business income, including services and pass-through fees — not just retail sales tax.',
      'Commercial real estate on Oahu is among the most expensive per square foot in the U.S.; outer islands are cheaper but smaller markets.',
    ],
    sosUrl: 'https://cca.hawaii.gov/breg/registration/dllc/',
    taxUrl: 'https://tax.hawaii.gov/geninfo/get/',
  },
  idaho: {
    slug: 'idaho',
    abbr: 'ID',
    name: 'Idaho',
    capital: 'Boise',
    registeredVehicles: '1.9M',
    topMetros: ['Boise', 'Meridian', 'Nampa', 'Idaho Falls', 'Pocatello'],
    costTier: 'low',
    costMultiplier: 0.85,
    llcFilingFee: '$100 (online) / $120 (paper)',
    llcFilingTimeDays: '7–10 business days online',
    salesTaxRate: '6.0% state + 0–3% local resort tax (range 6.0–9.0%)',
    needsStateBusinessLicense: false,
    needsAutomotiveRepairLicense: false,
    epaWasteTireProgram: false,
    startupCostRange: {
      mobile: '$30K–$72K',
      singleBay: '$81K–$187K',
      multiBay: '$170K–$357K',
    },
    marketNotes:
      'Idaho — particularly the Boise metro — has been one of the fastest-growing states by population and registered vehicles for the past decade. Studded snow tires are common; winter changeover demand is strong. Cost of entry is well below national average, though Boise commercial rents are rising fast.',
    whyHere: [
      'Boise metro is one of the fastest-growing in the U.S. — population up 15%+ since 2020.',
      'Universal winter tire / studded tire demand creates a clean seasonal spike.',
      'Low labor costs and no state automotive repair license requirement.',
    ],
    watchouts: [
      'Boise commercial rents have risen sharply; secondary cities (Nampa, Meridian) offer better economics.',
      'No statewide scrap tire program — disposal arrangements vary by county; verify before opening.',
      'Studded tire season (Oct 1 – Apr 30) is enforced; storage and changeover logistics need planning.',
    ],
    sosUrl: 'https://sos.idaho.gov/business/',
    taxUrl: 'https://tax.idaho.gov/taxes/sales-use/',
  },
  illinois: {
    slug: 'illinois',
    abbr: 'IL',
    name: 'Illinois',
    capital: 'Springfield',
    registeredVehicles: '10.4M',
    topMetros: ['Chicago', 'Aurora', 'Rockford', 'Joliet', 'Naperville'],
    costTier: 'high',
    costMultiplier: 1.25,
    llcFilingFee: '$150 + $75 annual report',
    llcFilingTimeDays: '5–10 business days online',
    salesTaxRate: '6.25% state + 0.25–4.75% local (range 6.25–11.0%)',
    needsStateBusinessLicense: false,
    needsAutomotiveRepairLicense: false,
    epaWasteTireProgram: true,
    epaProgramName: 'Illinois EPA Used and Waste Tire Program',
    epaTireDisposalFee: '$2.50 per new tire sold (state)',
    startupCostRange: {
      mobile: '$45K–$105K',
      singleBay: '$118K–$275K',
      multiBay: '$250K–$525K',
    },
    marketNotes:
      'Illinois is anchored by the Chicago metro — 9M+ people and one of the densest commercial fleet bases in the country (logistics, last-mile, rideshare, construction). Cook County and Chicago add their own taxes and a separate Chicago tire fee (currently $1/tire) on top of the state surcharge. Outside Chicago, costs drop substantially.',
    whyHere: [
      'Chicago metro fleet density (logistics, rideshare, construction) is among the highest in the country.',
      'Aurora and Naperville suburbs combine strong household income with growing populations.',
      'Winter tire seasonal demand creates predictable revenue patterns.',
    ],
    watchouts: [
      'Chicago adds a $1/tire fee on top of the $2.50 state fee — total $3.50 per tire to disclose.',
      'Cook County commercial property taxes are among the highest in the country.',
      'Annual LLC report ($75) plus rising state filing costs erode the low-cost-state value proposition.',
    ],
    sosUrl: 'https://www.ilsos.gov/departments/business_services/home.html',
    taxUrl: 'https://tax.illinois.gov/research/taxinformation/sales/rot.html',
    epaUrl: 'https://epa.illinois.gov/topics/waste-management/waste-disposal/used-tires.html',
  },
  indiana: {
    slug: 'indiana',
    abbr: 'IN',
    name: 'Indiana',
    capital: 'Indianapolis',
    registeredVehicles: '5.7M',
    topMetros: ['Indianapolis', 'Fort Wayne', 'Evansville', 'South Bend', 'Carmel'],
    costTier: 'low',
    costMultiplier: 0.85,
    llcFilingFee: '$95 (online) / $100 (paper)',
    llcFilingTimeDays: '1–3 business days online',
    salesTaxRate: '7.0% state (no local add-on)',
    needsStateBusinessLicense: false,
    needsAutomotiveRepairLicense: false,
    epaWasteTireProgram: true,
    epaProgramName: 'IDEM Waste Tire Management Program',
    epaTireDisposalFee: '$0.25 per new tire sold (state)',
    startupCostRange: {
      mobile: '$30K–$72K',
      singleBay: '$81K–$187K',
      multiBay: '$170K–$357K',
    },
    marketNotes:
      'Indiana has one of the best risk-adjusted markets in the Midwest. Flat 7% sales tax (no local add-ons) simplifies pricing; Indianapolis is a major logistics hub thanks to FedEx\'s second-largest global hub at IND; manufacturing fleet base is deep. Low LLC filing fee, fast turnaround, no repair license.',
    whyHere: [
      'Indianapolis FedEx hub (second-largest globally) drives massive logistics fleet demand.',
      'Flat 7% sales tax — no local stacking — makes pricing and POS configuration simple.',
      '$95 LLC filing and 1–3 day turnaround are among the fastest in the U.S.',
    ],
    watchouts: [
      'Winter salt and slush damage equipment and consumables faster than southern states.',
      'Manufacturing-region labor pools are competitive; tire shops compete with auto plants for techs.',
      'Northern Indiana lake-effect snow creates intense but short winter demand spikes.',
    ],
    sosUrl: 'https://inbiz.in.gov/',
    taxUrl: 'https://www.in.gov/dor/business-tax/sales-tax/',
    epaUrl: 'https://www.in.gov/idem/recycle/recycling-programs/waste-tire-management-program/',
  },
  iowa: {
    slug: 'iowa',
    abbr: 'IA',
    name: 'Iowa',
    capital: 'Des Moines',
    registeredVehicles: '3.4M',
    topMetros: ['Des Moines', 'Cedar Rapids', 'Davenport', 'Sioux City', 'Iowa City'],
    costTier: 'low',
    costMultiplier: 0.85,
    llcFilingFee: '$50',
    llcFilingTimeDays: '1–3 business days online',
    salesTaxRate: '6.0% state + 0–1% local option (range 6.0–7.0%)',
    needsStateBusinessLicense: false,
    needsAutomotiveRepairLicense: false,
    epaWasteTireProgram: true,
    epaProgramName: 'Iowa DNR Waste Tire Management',
    epaTireDisposalFee: 'Set by retailer; no state per-tire fee',
    startupCostRange: {
      mobile: '$30K–$72K',
      singleBay: '$81K–$187K',
      multiBay: '$170K–$357K',
    },
    marketNotes:
      'Iowa offers very low entry costs and stable demand. The state\'s vehicle base is dominated by older trucks and SUVs (agriculture, construction), generating strong replacement and seasonal-changeover revenue. Des Moines has been a steady-growth metro; Cedar Rapids and Davenport (Quad Cities) anchor smaller markets.',
    whyHere: [
      '$50 LLC filing fee and 1–3 day turnaround — among the cheapest and fastest.',
      'Agriculture and construction fleet base supports strong off-road and LT tire demand.',
      'Stable population and vehicle base — low churn, predictable revenue.',
    ],
    watchouts: [
      'Rural labor pools are thin for certified techs; plan to recruit early.',
      'Winter salt damage and ice-related collision business mean insurance claims patterns differ from southern states.',
      'Cedar Rapids derecho (2020) showed the state\'s exposure to severe wind events — structural property insurance has risen since.',
    ],
    sosUrl: 'https://sos.iowa.gov/business/',
    taxUrl: 'https://tax.iowa.gov/iowa-sales-and-use-tax',
    epaUrl: 'https://www.iowadnr.gov/Environmental-Protection/Land-Quality/Waste-Tire-Management',
  },
  kansas: {
    slug: 'kansas',
    abbr: 'KS',
    name: 'Kansas',
    capital: 'Topeka',
    registeredVehicles: '2.5M',
    topMetros: ['Wichita', 'Overland Park', 'Kansas City (KS)', 'Topeka', 'Olathe'],
    costTier: 'low',
    costMultiplier: 0.85,
    llcFilingFee: '$160 (online) / $165 (paper)',
    llcFilingTimeDays: '1–2 business days online',
    salesTaxRate: '6.5% state + 0–4.25% local (range 6.5–10.75%)',
    needsStateBusinessLicense: false,
    needsAutomotiveRepairLicense: false,
    epaWasteTireProgram: true,
    epaProgramName: 'KDHE Waste Tire Program',
    epaTireDisposalFee: '$0.25 per new tire sold (state)',
    startupCostRange: {
      mobile: '$30K–$72K',
      singleBay: '$81K–$187K',
      multiBay: '$170K–$357K',
    },
    marketNotes:
      'Kansas combines a Wichita aerospace-manufacturing base with the Kansas City metro spillover (Overland Park, Olathe are some of the fastest-growing suburbs in the Midwest). The trucking corridor along I-70 and I-35 supports commercial fleet demand. Filing fees are mid-pack but turnaround is fast.',
    whyHere: [
      'Wichita aerospace cluster (Spirit AeroSystems, Textron, Bombardier) drives industrial vehicle demand.',
      'Overland Park/Olathe suburbs are some of the fastest-growing in the Midwest.',
      'I-70 and I-35 trucking corridors support commercial recurring revenue.',
    ],
    watchouts: [
      'Local sales tax stacking can push combined rate above 10% in Wichita and parts of Johnson County.',
      'Tornado-belt exposure raises commercial property insurance premiums.',
      'Western Kansas labor pool is thin — most viable markets are in the I-35/I-70 belt.',
    ],
    sosUrl: 'https://sos.ks.gov/business/business.html',
    taxUrl: 'https://www.ksrevenue.gov/bustaxtypessales.html',
    epaUrl: 'https://www.kdhe.ks.gov/255/Waste-Tires',
  },
  kentucky: {
    slug: 'kentucky',
    abbr: 'KY',
    name: 'Kentucky',
    capital: 'Frankfort',
    registeredVehicles: '3.9M',
    topMetros: ['Louisville', 'Lexington', 'Bowling Green', 'Owensboro', 'Covington'],
    costTier: 'low',
    costMultiplier: 0.85,
    llcFilingFee: '$40',
    llcFilingTimeDays: '1–3 business days online',
    salesTaxRate: '6.0% state (no local add-on)',
    needsStateBusinessLicense: false,
    needsAutomotiveRepairLicense: false,
    epaWasteTireProgram: true,
    epaProgramName: 'KY Energy and Environment Cabinet Waste Tire Program',
    epaTireDisposalFee: '$2 per new tire sold (state)',
    startupCostRange: {
      mobile: '$30K–$72K',
      singleBay: '$81K–$187K',
      multiBay: '$170K–$357K',
    },
    marketNotes:
      'Kentucky has one of the cheapest LLC filing fees in the country ($40) and a flat 6% sales tax with no local stacking. Louisville is a major UPS Worldport hub and Toyota\'s largest North American plant is in Georgetown — combined, the state has unusual logistics and manufacturing fleet density for its size.',
    whyHere: [
      '$40 LLC filing fee — one of the cheapest in the U.S.',
      'UPS Worldport (Louisville) and Toyota Georgetown plant drive logistics and manufacturing fleet demand.',
      'Flat 6% sales tax with no local add-on simplifies pricing.',
    ],
    watchouts: [
      'Eastern Kentucky markets are thin and aging — focus on Louisville, Lexington, and Northern Kentucky (Cincinnati spillover).',
      '$2/tire state environmental fee is at the higher end — disclose clearly.',
      'Coal-region economic decline has reshaped commercial fleet demand in eastern counties.',
    ],
    sosUrl: 'https://sos.ky.gov/bus/business-filings/',
    taxUrl: 'https://revenue.ky.gov/Business/Sales-Use-Tax/',
    epaUrl: 'https://eec.ky.gov/Environmental-Protection/Waste/recycling/Pages/Waste-Tires.aspx',
  },
  louisiana: {
    slug: 'louisiana',
    abbr: 'LA',
    name: 'Louisiana',
    capital: 'Baton Rouge',
    registeredVehicles: '3.8M',
    topMetros: ['New Orleans', 'Baton Rouge', 'Shreveport', 'Lafayette', 'Lake Charles'],
    costTier: 'low',
    costMultiplier: 0.85,
    llcFilingFee: '$100',
    llcFilingTimeDays: '3–5 business days online',
    salesTaxRate: '4.45% state + 0–7% local (range 4.45–11.45%)',
    needsStateBusinessLicense: false,
    needsAutomotiveRepairLicense: false,
    epaWasteTireProgram: true,
    epaProgramName: 'LDEQ Waste Tire Program',
    epaTireDisposalFee: '$2.25 per new passenger tire / $5 per medium truck tire',
    startupCostRange: {
      mobile: '$30K–$72K',
      singleBay: '$81K–$187K',
      multiBay: '$170K–$357K',
    },
    marketNotes:
      'Louisiana combines low entry costs with a unique hazard profile. Hurricane exposure is real and insurance markets reflect it. New Orleans and Baton Rouge anchor the state\'s vehicle base; Shreveport and Lafayette add meaningful secondary markets. Combined local + state sales tax often exceeds 10%.',
    whyHere: [
      'Low labor and rent costs across the state.',
      'Port of South Louisiana and Baton Rouge industrial corridor drive commercial fleet demand.',
      'Hot, humid climate accelerates tire wear — replacement intervals shorter than national average.',
    ],
    watchouts: [
      'Combined sales tax can exceed 11% in parts of Orleans and East Baton Rouge parishes — disclose clearly.',
      'Hurricane exposure drives commercial property and business interruption insurance premiums 30–50% above national average.',
      '$2.25/passenger and $5/truck tire state fees are on the high end — model into pricing.',
    ],
    sosUrl: 'https://www.sos.la.gov/BusinessServices/Pages/default.aspx',
    taxUrl: 'https://revenue.louisiana.gov/SalesTax',
    epaUrl: 'https://www.deq.louisiana.gov/page/waste-tire-program',
  },
  maine: {
    slug: 'maine',
    abbr: 'ME',
    name: 'Maine',
    capital: 'Augusta',
    registeredVehicles: '1.2M',
    topMetros: ['Portland', 'Lewiston', 'Bangor', 'South Portland', 'Auburn'],
    costTier: 'mid',
    costMultiplier: 1.0,
    llcFilingFee: '$175',
    llcFilingTimeDays: '5–10 business days standard',
    salesTaxRate: '5.5% state (no local add-on)',
    needsStateBusinessLicense: false,
    needsAutomotiveRepairLicense: false,
    epaWasteTireProgram: true,
    epaProgramName: 'Maine DEP Waste Tire Program',
    epaTireDisposalFee: '$1 per new tire sold (state)',
    startupCostRange: {
      mobile: '$35K–$85K',
      singleBay: '$95K–$220K',
      multiBay: '$200K–$420K',
    },
    marketNotes:
      'Maine is small in absolute terms but has near-universal winter tire demand and an aging vehicle base that supports steady replacement work. Portland is the dominant metro and has been growing modestly. Flat 5.5% sales tax simplifies pricing.',
    whyHere: [
      'Universal winter tire demand — studded tires are legal Oct 1 – May 1 and widely used.',
      'Flat 5.5% state sales tax with no local add-on.',
      'Aging vehicle fleet supports steady replacement and repair revenue.',
    ],
    watchouts: [
      'LLC filing fee ($175) is at the higher end relative to neighboring states.',
      'Winter is long and harsh; budget 15–20% higher equipment maintenance.',
      'Rural Maine markets outside Portland/Bangor are very thin — site selection matters.',
    ],
    sosUrl: 'https://www.maine.gov/sos/cec/corp/index.html',
    taxUrl: 'https://www.maine.gov/revenue/taxes/sales-use-service-provider-tax',
    epaUrl: 'https://www.maine.gov/dep/waste/solidwaste/tires.html',
  },
  maryland: {
    slug: 'maryland',
    abbr: 'MD',
    name: 'Maryland',
    capital: 'Annapolis',
    registeredVehicles: '4.7M',
    topMetros: ['Baltimore', 'Silver Spring', 'Frederick', 'Rockville', 'Gaithersburg'],
    costTier: 'high',
    costMultiplier: 1.25,
    llcFilingFee: '$100 + $300 annual report',
    llcFilingTimeDays: '4–6 weeks standard; 7 days with $50 expedite',
    salesTaxRate: '6.0% state (no local add-on)',
    needsStateBusinessLicense: false,
    needsAutomotiveRepairLicense: true,
    automotiveRepairAgency: 'Maryland MVA Automotive Repair Facility Registration',
    epaWasteTireProgram: true,
    epaProgramName: 'MDE Scrap Tire Program',
    epaTireDisposalFee: '$0.80 per new tire sold (state)',
    startupCostRange: {
      mobile: '$45K–$105K',
      singleBay: '$118K–$275K',
      multiBay: '$250K–$525K',
    },
    marketNotes:
      'Maryland has strong household incomes (DC suburbs) and a meaningful fleet base (Port of Baltimore, federal contractors). MVA Automotive Repair Facility registration is required — non-trivial paperwork and a $300 annual LLC report add to fixed costs. Flat 6% sales tax simplifies pricing.',
    whyHere: [
      'DC-suburb household incomes (Montgomery, Howard counties) drive premium-tire demand.',
      'Port of Baltimore drives commercial trucking and intermodal fleet demand.',
      'Flat 6% sales tax with no local add-on simplifies POS and pricing.',
    ],
    watchouts: [
      'MVA Automotive Repair Facility registration is required before opening — start the application early.',
      '$300 annual report fee is mandatory regardless of revenue.',
      'Standard LLC filing turnaround (4–6 weeks) is slow; budget the $50 expedite fee.',
    ],
    sosUrl: 'https://egov.maryland.gov/businessexpress',
    taxUrl: 'https://www.marylandtaxes.gov/business/sales-use/index.php',
    epaUrl: 'https://mde.maryland.gov/programs/land/RecyclingandOperationsprogram/Pages/scraptire.aspx',
    repairLicenseUrl: 'https://mva.maryland.gov/businesses/Pages/automotive-repair-facility.aspx',
  },
  massachusetts: {
    slug: 'massachusetts',
    abbr: 'MA',
    name: 'Massachusetts',
    capital: 'Boston',
    registeredVehicles: '5.4M',
    topMetros: ['Boston', 'Worcester', 'Springfield', 'Cambridge', 'Lowell'],
    costTier: 'high',
    costMultiplier: 1.25,
    llcFilingFee: '$500 + $500 annual report',
    llcFilingTimeDays: '1–3 business days online',
    salesTaxRate: '6.25% state (no local add-on)',
    needsStateBusinessLicense: false,
    needsAutomotiveRepairLicense: false,
    epaWasteTireProgram: true,
    epaProgramName: 'MassDEP Waste Tire Management',
    epaTireDisposalFee: 'Set by retailer; no state per-tire fee',
    startupCostRange: {
      mobile: '$45K–$105K',
      singleBay: '$118K–$275K',
      multiBay: '$250K–$525K',
    },
    marketNotes:
      'Massachusetts is high-revenue but high-fixed-cost. The $500 LLC filing fee plus $500 annual report is among the highest in the U.S. Boston metro household incomes and density support premium tire and run-flat demand. Flat 6.25% sales tax simplifies pricing.',
    whyHere: [
      'Boston metro household incomes drive premium and run-flat tire demand.',
      'Flat 6.25% sales tax with no local add-on.',
      'Mass DOT mandatory annual inspection program drives steady walk-in traffic for adjacent services.',
    ],
    watchouts: [
      '$500 LLC filing fee + $500 annual report — among the most expensive in the U.S.',
      'Boston commercial real estate is among the priciest; Worcester and Springfield offer better unit economics.',
      'Winter salt damages equipment and tools; budget elevated maintenance.',
    ],
    sosUrl: 'https://www.sec.state.ma.us/divisions/corporations/corporations.htm',
    taxUrl: 'https://www.mass.gov/sales-and-use-tax',
    epaUrl: 'https://www.mass.gov/info-details/managing-waste-tires-in-massachusetts',
  },
  michigan: {
    slug: 'michigan',
    abbr: 'MI',
    name: 'Michigan',
    capital: 'Lansing',
    registeredVehicles: '8.4M',
    topMetros: ['Detroit', 'Grand Rapids', 'Warren', 'Sterling Heights', 'Ann Arbor'],
    costTier: 'mid',
    costMultiplier: 1.0,
    llcFilingFee: '$50 + $25 annual statement',
    llcFilingTimeDays: '3–5 business days online',
    salesTaxRate: '6.0% state (no local add-on)',
    needsStateBusinessLicense: false,
    needsAutomotiveRepairLicense: true,
    automotiveRepairAgency: 'Michigan Department of State — Motor Vehicle Service and Repair Facility Registration',
    epaWasteTireProgram: true,
    epaProgramName: 'EGLE Scrap Tire Program',
    epaTireDisposalFee: '$1.50 per vehicle title transfer (funds program; not per-tire)',
    startupCostRange: {
      mobile: '$35K–$85K',
      singleBay: '$95K–$220K',
      multiBay: '$200K–$420K',
    },
    marketNotes:
      'Michigan requires Motor Vehicle Service and Repair Facility registration through the Secretary of State — separate from your LLC filing — and at least one Certified Mechanic on staff for any work beyond minor services. Tire-only work has carve-outs, but verify your scope. Flat 6% sales tax simplifies pricing.',
    whyHere: [
      'Detroit auto-industry fleet density (Big Three, suppliers, tooling shops) drives commercial demand.',
      '$50 LLC filing fee — among the cheapest in the U.S.',
      'Flat 6% sales tax with no local add-on.',
    ],
    watchouts: [
      'Motor Vehicle Service and Repair Facility registration is required for repair work — verify whether your service scope triggers the requirement.',
      'Mechanic certification (Michigan-specific) is required for many repair categories; tire-only shops may be exempt but the line is narrow.',
      'Winter salt is among the worst in the country — equipment and consumable life shortened 15–20%.',
    ],
    sosUrl: 'https://www.michigan.gov/lara/bureau-list/cscl',
    taxUrl: 'https://www.michigan.gov/taxes/business-taxes/sales-use-tax',
    epaUrl: 'https://www.michigan.gov/egle/about/organization/materials-management/scrap-tires',
    repairLicenseUrl: 'https://www.michigan.gov/sos/business-services/mechanics-repair-facilities',
  },
  minnesota: {
    slug: 'minnesota',
    abbr: 'MN',
    name: 'Minnesota',
    capital: 'Saint Paul',
    registeredVehicles: '5.5M',
    topMetros: ['Minneapolis', 'Saint Paul', 'Rochester', 'Duluth', 'Bloomington'],
    costTier: 'mid',
    costMultiplier: 1.0,
    llcFilingFee: '$155 (online) / $135 (paper)',
    llcFilingTimeDays: '1–3 business days online',
    salesTaxRate: '6.875% state + 0–2% local (range 6.875–8.875%)',
    needsStateBusinessLicense: false,
    needsAutomotiveRepairLicense: false,
    epaWasteTireProgram: true,
    epaProgramName: 'MPCA Waste Tire Program',
    epaTireDisposalFee: 'Set by retailer; no state per-tire fee',
    startupCostRange: {
      mobile: '$35K–$85K',
      singleBay: '$95K–$220K',
      multiBay: '$200K–$420K',
    },
    marketNotes:
      'Minnesota has strong winter tire demand (one of the highest seasonal-changeover rates in the country) and a stable Twin Cities economy with deep corporate fleet exposure (Target, 3M, UnitedHealth, Best Buy HQs). Rural northern Minnesota markets are thin but underserved.',
    whyHere: [
      'Among the highest winter-tire / seasonal-changeover rates in the country.',
      'Twin Cities Fortune 500 concentration (Target, 3M, UnitedHealth, US Bank) drives corporate fleet demand.',
      'Stable population and vehicle base — low churn, predictable revenue.',
    ],
    watchouts: [
      'Winter is long and severe; budget 15–20% higher equipment maintenance and snow removal costs.',
      'Twin Cities commercial real estate is competitive — secondary metros (Rochester, Duluth) offer better economics.',
      'Storage logistics for seasonal tire swaps require dedicated space — factor into shop layout.',
    ],
    sosUrl: 'https://www.sos.state.mn.us/business-liens/start-a-business/',
    taxUrl: 'https://www.revenue.state.mn.us/sales-and-use-tax',
    epaUrl: 'https://www.pca.state.mn.us/business-with-us/waste-tires',
  },
  mississippi: {
    slug: 'mississippi',
    abbr: 'MS',
    name: 'Mississippi',
    capital: 'Jackson',
    registeredVehicles: '2.2M',
    topMetros: ['Jackson', 'Gulfport', 'Southaven', 'Biloxi', 'Hattiesburg'],
    costTier: 'low',
    costMultiplier: 0.85,
    llcFilingFee: '$50',
    llcFilingTimeDays: '2–5 business days online',
    salesTaxRate: '7.0% state (no local add-on; few local exceptions)',
    needsStateBusinessLicense: false,
    needsAutomotiveRepairLicense: false,
    epaWasteTireProgram: true,
    epaProgramName: 'MDEQ Waste Tire Program',
    epaTireDisposalFee: '$1 per new passenger tire / $2 per medium truck tire',
    startupCostRange: {
      mobile: '$30K–$72K',
      singleBay: '$81K–$187K',
      multiBay: '$170K–$357K',
    },
    marketNotes:
      'Mississippi offers very low entry costs and a flat 7% sales tax. Southaven (Memphis spillover) is the fastest-growing area. Gulf Coast (Gulfport, Biloxi) has tourism and gaming fleet demand. Vehicle base is smaller than neighboring Alabama or Louisiana.',
    whyHere: [
      '$50 LLC filing fee — among the cheapest in the U.S.',
      'Flat 7% sales tax with virtually no local add-on simplifies pricing.',
      'Southaven (Memphis suburb) is the fastest-growing area and underserved.',
    ],
    watchouts: [
      'Hurricane exposure on the Gulf Coast drives commercial property insurance premiums up.',
      'Rural labor pools are thin; recruit early and offer training.',
      'Overall vehicle base is smaller than neighbors — focus on the Jackson, Southaven, and Gulf Coast markets.',
    ],
    sosUrl: 'https://www.sos.ms.gov/business-services',
    taxUrl: 'https://www.dor.ms.gov/business/sales-and-use-tax',
    epaUrl: 'https://www.mdeq.ms.gov/waste/solid-waste/waste-tires/',
  },
  missouri: {
    slug: 'missouri',
    abbr: 'MO',
    name: 'Missouri',
    capital: 'Jefferson City',
    registeredVehicles: '5.5M',
    topMetros: ['Kansas City', 'St. Louis', 'Springfield', 'Columbia', 'Independence'],
    costTier: 'low',
    costMultiplier: 0.85,
    llcFilingFee: '$50 (online) / $105 (paper)',
    llcFilingTimeDays: '1–3 business days online',
    salesTaxRate: '4.225% state + 0–5.875% local (range 4.225–10.1%)',
    needsStateBusinessLicense: false,
    needsAutomotiveRepairLicense: false,
    epaWasteTireProgram: true,
    epaProgramName: 'Missouri DNR Waste Tire Program',
    epaTireDisposalFee: '$0.50 per new tire sold (state)',
    startupCostRange: {
      mobile: '$30K–$72K',
      singleBay: '$81K–$187K',
      multiBay: '$170K–$357K',
    },
    marketNotes:
      'Missouri sits at the I-70 / I-44 / I-29 crossroads and has unusually strong logistics fleet density for its population. Kansas City and St. Louis are both deep commercial markets. $50 LLC filing fee online and no state automotive repair license keep entry friction low.',
    whyHere: [
      'I-70 / I-44 / I-29 trucking corridors converge in Missouri — strong commercial fleet demand.',
      '$50 online LLC filing fee — among the cheapest in the U.S.',
      'Kansas City and St. Louis are deep, established commercial markets.',
    ],
    watchouts: [
      'Local sales tax stacking can push combined rate above 10% in parts of St. Louis County and Kansas City.',
      'St. Louis City vs. County tax and licensing rules differ — verify your jurisdiction carefully.',
      'Tornado-belt exposure raises commercial property insurance premiums.',
    ],
    sosUrl: 'https://www.sos.mo.gov/business',
    taxUrl: 'https://dor.mo.gov/taxation/business/tax-types/sales-use/',
    epaUrl: 'https://dnr.mo.gov/waste-recycling/businesses/waste-tires',
  },
  montana: {
    slug: 'montana',
    abbr: 'MT',
    name: 'Montana',
    capital: 'Helena',
    registeredVehicles: '1.3M',
    topMetros: ['Billings', 'Missoula', 'Great Falls', 'Bozeman', 'Helena'],
    costTier: 'mid',
    costMultiplier: 1.0,
    llcFilingFee: '$35',
    llcFilingTimeDays: '5–7 business days online',
    salesTaxRate: 'No state sales tax (limited resort-area local sales tax)',
    needsStateBusinessLicense: false,
    needsAutomotiveRepairLicense: false,
    epaWasteTireProgram: false,
    startupCostRange: {
      mobile: '$35K–$85K',
      singleBay: '$95K–$220K',
      multiBay: '$200K–$420K',
    },
    marketNotes:
      'Montana has no general state sales tax — customer pricing is unusually clean. The vehicle base is small but skewed toward trucks and SUVs (agriculture, oil/gas, construction). Bozeman and Missoula have been growing fast post-2020 thanks to remote-work migration. $35 LLC filing is the cheapest in the U.S.',
    whyHere: [
      '$35 LLC filing fee — cheapest in the U.S.',
      'No state sales tax — customer-facing pricing is simpler and feels cheaper.',
      'Truck/SUV-heavy vehicle mix supports higher-revenue LT and off-road tire sales.',
    ],
    watchouts: [
      'Inventory logistics: distributors deliver less frequently; build deeper inventory buffers.',
      'No state EPA waste tire program — disposal arrangements vary by county; verify before opening.',
      'Studded tire season and extreme winter weather drive demand but also operating costs.',
    ],
    sosUrl: 'https://sosmt.gov/business/',
    taxUrl: 'https://mtrevenue.gov/taxes/',
  },
  nebraska: {
    slug: 'nebraska',
    abbr: 'NE',
    name: 'Nebraska',
    capital: 'Lincoln',
    registeredVehicles: '2.0M',
    topMetros: ['Omaha', 'Lincoln', 'Bellevue', 'Grand Island'],
    costTier: 'low',
    costMultiplier: 0.85,
    llcFilingFee: '$100 + publication requirement (~$40–$200)',
    llcFilingTimeDays: '2–5 business days online',
    salesTaxRate: '5.5% state + 0–2% local (range 5.5–7.5%)',
    needsStateBusinessLicense: false,
    needsAutomotiveRepairLicense: false,
    epaWasteTireProgram: true,
    epaProgramName: 'NDEE Scrap Tire Program',
    epaTireDisposalFee: '$1 per new tire sold (state)',
    startupCostRange: {
      mobile: '$30K–$72K',
      singleBay: '$81K–$187K',
      multiBay: '$170K–$357K',
    },
    marketNotes:
      'Nebraska\'s tire market is anchored by Omaha (Berkshire Hathaway, Mutual of Omaha, Union Pacific HQs) and Lincoln (state government, University of Nebraska). The Union Pacific rail hub and I-80 trucking corridor add significant commercial fleet demand. LLC publication requirement adds a modest cost.',
    whyHere: [
      'Omaha corporate fleet base (Berkshire, Mutual of Omaha, Union Pacific) drives commercial demand.',
      'I-80 trucking corridor through Omaha and Lincoln supports recurring commercial revenue.',
      'Low labor and rent costs — among the best risk-adjusted Midwest markets.',
    ],
    watchouts: [
      'LLC publication requirement adds ~$40–$200 to formation cost; budget the time.',
      'Western Nebraska markets are very thin — focus on the Omaha–Lincoln corridor.',
      'Winter and tornado exposure raise commercial property insurance.',
    ],
    sosUrl: 'https://sos.nebraska.gov/business-services',
    taxUrl: 'https://revenue.nebraska.gov/businesses/sales-and-use-tax',
    epaUrl: 'https://dee.ne.gov/Publica.nsf/Pages/WAS148',
  },
  nevada: {
    slug: 'nevada',
    abbr: 'NV',
    name: 'Nevada',
    capital: 'Carson City',
    registeredVehicles: '2.6M',
    topMetros: ['Las Vegas', 'Henderson', 'Reno', 'North Las Vegas', 'Sparks'],
    costTier: 'mid',
    costMultiplier: 1.0,
    llcFilingFee: '$425 ($75 Articles + $150 Initial List + $200 State Business License)',
    llcFilingTimeDays: '5–7 business days online',
    salesTaxRate: '6.85% state + 0–1.525% local (range 6.85–8.375%)',
    needsStateBusinessLicense: true,
    needsAutomotiveRepairLicense: true,
    automotiveRepairAgency: 'Nevada DMV Motor Vehicle Industry Licensing (Garage / Body Shop Registration)',
    epaWasteTireProgram: true,
    epaProgramName: 'NDEP Waste Tire Management',
    epaTireDisposalFee: '$1 per new tire sold (state)',
    startupCostRange: {
      mobile: '$35K–$85K',
      singleBay: '$95K–$220K',
      multiBay: '$200K–$420K',
    },
    marketNotes:
      'Nevada has no state income tax, but the State Business License ($200/year, $500 for corporations) and DMV Garage Registration combine to make formation costlier than headline LLC fees suggest. Las Vegas tourism rental fleets and Reno logistics expansion (Tesla, Switch, Amazon) drive strong commercial demand.',
    whyHere: [
      'No state income tax preserves owner take-home.',
      'Reno Tahoe Industrial Center (Tesla Gigafactory, Switch, Amazon) drives commercial fleet demand.',
      'Las Vegas rental and tourism fleet rotation creates recurring demand.',
    ],
    watchouts: [
      'Nevada State Business License is required ($200/year for LLCs) — separate from local licensing.',
      'Nevada DMV Garage Registration is required for repair work; tire-only work has carve-outs but verify.',
      'Las Vegas summer heat exceeds 110°F — accelerates tire wear but punishes outdoor and mobile work.',
    ],
    sosUrl: 'https://www.nvsos.gov/sos/businesses',
    taxUrl: 'https://tax.nv.gov/Sales/Sales_Use_Tax/',
    epaUrl: 'https://ndep.nv.gov/waste/solid-waste/waste-tires',
    repairLicenseUrl: 'https://dmv.nv.gov/businesses.htm',
  },
  'new-hampshire': {
    slug: 'new-hampshire',
    abbr: 'NH',
    name: 'New Hampshire',
    capital: 'Concord',
    registeredVehicles: '1.4M',
    topMetros: ['Manchester', 'Nashua', 'Concord', 'Dover', 'Portsmouth'],
    costTier: 'mid',
    costMultiplier: 1.0,
    llcFilingFee: '$100 + $100 annual report',
    llcFilingTimeDays: '3–7 business days online',
    salesTaxRate: 'No state sales tax',
    needsStateBusinessLicense: false,
    needsAutomotiveRepairLicense: false,
    epaWasteTireProgram: true,
    epaProgramName: 'NHDES Waste Tire Management',
    epaTireDisposalFee: 'Set by retailer; no state per-tire fee',
    startupCostRange: {
      mobile: '$35K–$85K',
      singleBay: '$95K–$220K',
      multiBay: '$200K–$420K',
    },
    marketNotes:
      'New Hampshire has no state sales tax and no state income tax — customer pricing is clean and owner take-home is high. Manchester and Nashua are commuter-corridor metros with steady demand; Boston metro spillover keeps household incomes high. Winter tire demand is strong.',
    whyHere: [
      'No state sales tax — customer-facing pricing is simpler and feels cheaper.',
      'No state income tax preserves owner take-home.',
      'Boston metro spillover keeps household incomes high in Nashua and Manchester.',
    ],
    watchouts: [
      'Annual report fee ($100) is mandatory.',
      'Small overall market — secondary metros are thin; site selection matters.',
      'Winter logistics and salt damage add 10–15% to OPEX.',
    ],
    sosUrl: 'https://www.sos.nh.gov/corporations',
    taxUrl: 'https://www.revenue.nh.gov/',
    epaUrl: 'https://www.des.nh.gov/waste/solid-waste/waste-tires',
  },
  'new-jersey': {
    slug: 'new-jersey',
    abbr: 'NJ',
    name: 'New Jersey',
    capital: 'Trenton',
    registeredVehicles: '6.3M',
    topMetros: ['Newark', 'Jersey City', 'Paterson', 'Elizabeth', 'Edison'],
    costTier: 'high',
    costMultiplier: 1.25,
    llcFilingFee: '$125 + $75 annual report',
    llcFilingTimeDays: '1–3 business days online',
    salesTaxRate: '6.625% state (no local add-on; UEZ areas reduced)',
    needsStateBusinessLicense: false,
    needsAutomotiveRepairLicense: false,
    epaWasteTireProgram: true,
    epaProgramName: 'NJDEP Waste Tire Management',
    epaTireDisposalFee: '$1.50 per new tire sold (state)',
    startupCostRange: {
      mobile: '$45K–$105K',
      singleBay: '$118K–$275K',
      multiBay: '$250K–$525K',
    },
    marketNotes:
      'New Jersey is dense — 6M+ registered vehicles in a small geographic footprint. Port Newark / Elizabeth is one of the largest container ports in the country and drives massive trucking and intermodal fleet demand. Real estate is expensive but customer density and commercial demand are unusually high.',
    whyHere: [
      'Port Newark / Elizabeth — one of the largest container ports in the U.S. — drives intense commercial fleet demand.',
      '6.3M registered vehicles in a compact area means high density per service radius.',
      'Flat 6.625% sales tax with no local add-on (UEZ zones get half-rate).',
    ],
    watchouts: [
      'Commercial real estate in northern NJ is among the priciest in the country.',
      'NJ inspection laws differ from NY/PA — verify your service scope and any inspection-station licensing rules.',
      'Winter salt and brine damage equipment and consumables.',
    ],
    sosUrl: 'https://www.njportal.com/DOR/BusinessFormation/',
    taxUrl: 'https://www.nj.gov/treasury/taxation/businesses/salestax/',
    epaUrl: 'https://www.nj.gov/dep/dshw/recycling/scrap_tire.htm',
  },
  'new-mexico': {
    slug: 'new-mexico',
    abbr: 'NM',
    name: 'New Mexico',
    capital: 'Santa Fe',
    registeredVehicles: '1.9M',
    topMetros: ['Albuquerque', 'Las Cruces', 'Rio Rancho', 'Santa Fe', 'Roswell'],
    costTier: 'low',
    costMultiplier: 0.85,
    llcFilingFee: '$50',
    llcFilingTimeDays: '7–10 business days online',
    salesTaxRate: '5.0% state Gross Receipts Tax + 0–4% local (range 5.0–9.0%)',
    needsStateBusinessLicense: false,
    needsAutomotiveRepairLicense: false,
    epaWasteTireProgram: true,
    epaProgramName: 'NMED Scrap Tire Program',
    epaTireDisposalFee: 'Set by retailer; no fixed state per-tire fee',
    startupCostRange: {
      mobile: '$30K–$72K',
      singleBay: '$81K–$187K',
      multiBay: '$170K–$357K',
    },
    marketNotes:
      'New Mexico is a low-cost entry market with a small but stable vehicle base. Albuquerque metro dominates. Permian Basin oilfield activity (Hobbs, Carlsbad, Roswell) creates significant commercial truck demand in the southeast. New Mexico uses a Gross Receipts Tax rather than a traditional sales tax — passed through to customer in practice.',
    whyHere: [
      '$50 LLC filing fee — among the cheapest in the U.S.',
      'Permian Basin oilfield activity (southeast NM) drives heavy commercial truck demand.',
      'Low rent and labor costs; minimal competition outside Albuquerque.',
    ],
    watchouts: [
      'Gross Receipts Tax structure differs from traditional sales tax — model carefully (it can apply to services).',
      'Albuquerque crime statistics affect commercial insurance premiums.',
      'Remote markets (Roswell, Hobbs) have inventory logistics challenges.',
    ],
    sosUrl: 'https://www.sos.nm.gov/business-services/',
    taxUrl: 'https://www.tax.newmexico.gov/businesses/gross-receipts-overview/',
    epaUrl: 'https://www.env.nm.gov/solid-waste/scrap-tires/',
  },
  'north-carolina': {
    slug: 'north-carolina',
    abbr: 'NC',
    name: 'North Carolina',
    capital: 'Raleigh',
    registeredVehicles: '8.5M',
    topMetros: ['Charlotte', 'Raleigh', 'Greensboro', 'Durham', 'Winston-Salem'],
    costTier: 'mid',
    costMultiplier: 1.0,
    llcFilingFee: '$125 + $200 annual report',
    llcFilingTimeDays: '5–7 business days online',
    salesTaxRate: '4.75% state + 2.0–2.75% local (range 6.75–7.5%)',
    needsStateBusinessLicense: false,
    needsAutomotiveRepairLicense: false,
    epaWasteTireProgram: true,
    epaProgramName: 'NCDEQ Scrap Tire Program',
    epaTireDisposalFee: '2% Scrap Tire Disposal Tax on new tire sales (in addition to sales tax)',
    startupCostRange: {
      mobile: '$35K–$85K',
      singleBay: '$95K–$220K',
      multiBay: '$200K–$420K',
    },
    marketNotes:
      'North Carolina is one of the strongest growth markets in the Southeast. Charlotte (banking, motorsports) and Raleigh–Durham (Research Triangle tech/biotech) are among the fastest-growing metros in the country. The 2% Scrap Tire Disposal Tax is charged in addition to regular sales tax — disclose clearly.',
    whyHere: [
      'Charlotte and Raleigh–Durham among the fastest-growing metros in the U.S.',
      'Motorsports cluster around Charlotte (NASCAR teams, performance shops) supports specialty tire demand.',
      'Research Triangle tech/biotech workforce drives premium-tire and household demand.',
    ],
    watchouts: [
      '$200 annual report fee is on the higher end relative to neighbors.',
      '2% Scrap Tire Disposal Tax is on top of sales tax — disclose on receipts.',
      'Charlotte and Raleigh commercial rents have risen 25%+ since 2020.',
    ],
    sosUrl: 'https://www.sosnc.gov/divisions/business_registration',
    taxUrl: 'https://www.ncdor.gov/taxes-forms/sales-and-use-tax',
    epaUrl: 'https://www.deq.nc.gov/about/divisions/waste-management/solid-waste-section/scrap-tire-program',
  },
  'north-dakota': {
    slug: 'north-dakota',
    abbr: 'ND',
    name: 'North Dakota',
    capital: 'Bismarck',
    registeredVehicles: '0.9M',
    topMetros: ['Fargo', 'Bismarck', 'Grand Forks', 'Minot', 'West Fargo'],
    costTier: 'low',
    costMultiplier: 0.85,
    llcFilingFee: '$135',
    llcFilingTimeDays: '5–10 business days online',
    salesTaxRate: '5.0% state + 0–3.5% local (range 5.0–8.5%)',
    needsStateBusinessLicense: false,
    needsAutomotiveRepairLicense: false,
    epaWasteTireProgram: true,
    epaProgramName: 'ND DEQ Waste Tire Program',
    epaTireDisposalFee: 'Set by retailer; no fixed state per-tire fee',
    startupCostRange: {
      mobile: '$30K–$72K',
      singleBay: '$81K–$187K',
      multiBay: '$170K–$357K',
    },
    marketNotes:
      'North Dakota\'s vehicle base is small but the Bakken oilfield (Williston, Watford City, Dickinson) generates outsized commercial truck demand. Fargo is the dominant population center and has been growing steadily. Winter tire demand is universal.',
    whyHere: [
      'Bakken oilfield activity drives heavy commercial truck demand in western counties.',
      'Universal winter tire / studded tire demand creates a guaranteed seasonal spike.',
      'Low labor and rent costs.',
    ],
    watchouts: [
      'Bakken commercial demand is oil-price-cyclical — model downside scenarios.',
      'Western ND inventory logistics are challenging; longer lead times required.',
      'Winter is among the harshest in the U.S.; equipment maintenance and snow removal add 15–20% to OPEX.',
    ],
    sosUrl: 'https://sos.nd.gov/business-services',
    taxUrl: 'https://www.tax.nd.gov/business/sales-and-use-tax',
    epaUrl: 'https://deq.nd.gov/WM/RecyclingProgram/WasteTires.aspx',
  },
  oklahoma: {
    slug: 'oklahoma',
    abbr: 'OK',
    name: 'Oklahoma',
    capital: 'Oklahoma City',
    registeredVehicles: '3.5M',
    topMetros: ['Oklahoma City', 'Tulsa', 'Norman', 'Broken Arrow', 'Edmond'],
    costTier: 'low',
    costMultiplier: 0.85,
    llcFilingFee: '$100',
    llcFilingTimeDays: '1–3 business days online',
    salesTaxRate: '4.5% state + 0–7% local (range 4.5–11.5%)',
    needsStateBusinessLicense: false,
    needsAutomotiveRepairLicense: false,
    epaWasteTireProgram: true,
    epaProgramName: 'ODEQ Waste Tire Recycling Program',
    epaTireDisposalFee: '$1 per new passenger tire / $3.50 per medium truck tire',
    startupCostRange: {
      mobile: '$30K–$72K',
      singleBay: '$81K–$187K',
      multiBay: '$170K–$357K',
    },
    marketNotes:
      'Oklahoma combines low entry costs with strong oil-and-gas fleet demand. Tulsa and Oklahoma City are both deep commercial markets. I-40 and I-35 trucking corridors converge in OKC. Local sales tax stacking can push combined rate above 10%, so pricing transparency matters.',
    whyHere: [
      'Oil-and-gas fleet base drives heavy commercial truck demand.',
      'I-40 / I-35 trucking corridor convergence in OKC supports recurring commercial revenue.',
      'Low rent and labor costs across the state.',
    ],
    watchouts: [
      'Local sales tax stacking can push combined rate above 11% in parts of OKC and Tulsa.',
      'Tornado-belt exposure raises commercial property insurance premiums.',
      'Oil-cyclical commercial demand — model downside scenarios.',
    ],
    sosUrl: 'https://www.sos.ok.gov/business/default.aspx',
    taxUrl: 'https://oklahoma.gov/tax/businesses/business-tax-types/sales-and-use-tax.html',
    epaUrl: 'https://www.deq.ok.gov/land-protection-division/recycling/waste-tire/',
  },
  oregon: {
    slug: 'oregon',
    abbr: 'OR',
    name: 'Oregon',
    capital: 'Salem',
    registeredVehicles: '3.4M',
    topMetros: ['Portland', 'Salem', 'Eugene', 'Gresham', 'Hillsboro'],
    costTier: 'mid',
    costMultiplier: 1.0,
    llcFilingFee: '$100 + $100 annual report',
    llcFilingTimeDays: '2–5 business days online',
    salesTaxRate: 'No state sales tax',
    needsStateBusinessLicense: false,
    needsAutomotiveRepairLicense: false,
    epaWasteTireProgram: true,
    epaProgramName: 'Oregon DEQ Waste Tire Program',
    epaTireDisposalFee: 'Set by retailer; no state per-tire fee',
    startupCostRange: {
      mobile: '$35K–$85K',
      singleBay: '$95K–$220K',
      multiBay: '$200K–$420K',
    },
    marketNotes:
      'Oregon has no state sales tax — customer pricing is clean. Portland metro accounts for the majority of registered vehicles. Studded tire season (Nov 1 – Mar 31) drives clear seasonal changeover demand. Oregon\'s Corporate Activity Tax (CAT) applies to gross receipts above $1M, which can matter for multi-bay operators.',
    whyHere: [
      'No state sales tax — customer-facing pricing is simpler and feels cheaper.',
      'Mandatory studded tire season window drives seasonal changeover demand.',
      'Portland metro household incomes support premium-tire demand.',
    ],
    watchouts: [
      'Corporate Activity Tax (CAT) applies to Oregon-source gross receipts over $1M (0.57% rate); model into scale planning.',
      'Portland commercial real estate is expensive; secondary metros (Salem, Eugene) offer better economics.',
      'Wet climate accelerates tire wear and pavement-related claims (hydroplaning).',
    ],
    sosUrl: 'https://sos.oregon.gov/business/Pages/default.aspx',
    taxUrl: 'https://www.oregon.gov/dor/programs/businesses/Pages/default.aspx',
    epaUrl: 'https://www.oregon.gov/deq/mm/sw/Pages/Tires.aspx',
  },
  pennsylvania: {
    slug: 'pennsylvania',
    abbr: 'PA',
    name: 'Pennsylvania',
    capital: 'Harrisburg',
    registeredVehicles: '10.8M',
    topMetros: ['Philadelphia', 'Pittsburgh', 'Allentown', 'Erie', 'Reading'],
    costTier: 'mid',
    costMultiplier: 1.0,
    llcFilingFee: '$125',
    llcFilingTimeDays: '7–10 business days online',
    salesTaxRate: '6.0% state + 0–2% local (Philadelphia 8.0%, Allegheny 7.0%)',
    needsStateBusinessLicense: false,
    needsAutomotiveRepairLicense: false,
    epaWasteTireProgram: true,
    epaProgramName: 'PA DEP Waste Tire Program',
    epaTireDisposalFee: '$1 per new tire sold (state)',
    startupCostRange: {
      mobile: '$35K–$85K',
      singleBay: '$95K–$220K',
      multiBay: '$200K–$420K',
    },
    marketNotes:
      'Pennsylvania has 10.8M registered vehicles and a deep manufacturing and logistics base (Lehigh Valley distribution hubs, Pittsburgh industrial). Mandatory annual safety inspection plus emissions inspection in many counties drives steady walk-in demand for shops that become certified inspection stations. PA inspection station licensing is a separate process worth exploring.',
    whyHere: [
      'Mandatory annual safety inspection drives steady walk-in traffic — certified inspection stations get a built-in funnel.',
      'Lehigh Valley has become one of the largest distribution clusters on the East Coast.',
      '10.8M registered vehicles in a single state — third-largest market east of the Mississippi.',
    ],
    watchouts: [
      'PA inspection station certification is a separate licensing process (PennDOT) — worth pursuing but adds 60–90 days.',
      'Philadelphia adds 2% local sales tax (8% combined); Allegheny County adds 1%.',
      'Winter salt damage is significant; budget elevated equipment maintenance.',
    ],
    sosUrl: 'https://www.dos.pa.gov/BusinessCharities/Business/Pages/default.aspx',
    taxUrl: 'https://www.revenue.pa.gov/TaxTypes/SUT/Pages/default.aspx',
    epaUrl: 'https://www.dep.pa.gov/Business/Land/Waste/Recycling/Pages/Waste-Tires.aspx',
  },
  'rhode-island': {
    slug: 'rhode-island',
    abbr: 'RI',
    name: 'Rhode Island',
    capital: 'Providence',
    registeredVehicles: '0.83M',
    topMetros: ['Providence', 'Warwick', 'Cranston', 'Pawtucket'],
    costTier: 'high',
    costMultiplier: 1.25,
    llcFilingFee: '$150 + $50 annual report',
    llcFilingTimeDays: '3–5 business days online',
    salesTaxRate: '7.0% state (no local add-on)',
    needsStateBusinessLicense: false,
    needsAutomotiveRepairLicense: true,
    automotiveRepairAgency: 'RI DMV Auto Body / Repair Shop Registration',
    epaWasteTireProgram: true,
    epaProgramName: 'RIDEM Waste Tire Management',
    epaTireDisposalFee: 'Set by retailer; no state per-tire fee',
    startupCostRange: {
      mobile: '$45K–$105K',
      singleBay: '$118K–$275K',
      multiBay: '$250K–$525K',
    },
    marketNotes:
      'Rhode Island is small but dense, with Providence anchoring the bulk of demand. DMV repair shop registration is required for any work beyond basic tire sales. Flat 7% sales tax simplifies pricing. Boston metro spillover supports premium-tire demand in northern RI.',
    whyHere: [
      'Flat 7% sales tax with no local add-on.',
      'Boston metro spillover supports premium-tire demand in northern RI.',
      'Compact geography — a single shop can serve a large share of the state.',
    ],
    watchouts: [
      'RI DMV registration is required; the application includes a site inspection.',
      'Small overall market — competition concentrated in Providence/Warwick.',
      'Winter salt damage shortens equipment life.',
    ],
    sosUrl: 'https://www.sos.ri.gov/divisions/business-services',
    taxUrl: 'https://tax.ri.gov/tax-sections/sales-excise',
    epaUrl: 'https://dem.ri.gov/programs/wastemanagement/',
    repairLicenseUrl: 'https://dmv.ri.gov/businesses/auto-body-shops',
  },
  'south-carolina': {
    slug: 'south-carolina',
    abbr: 'SC',
    name: 'South Carolina',
    capital: 'Columbia',
    registeredVehicles: '4.0M',
    topMetros: ['Charleston', 'Columbia', 'Greenville', 'Myrtle Beach', 'Spartanburg'],
    costTier: 'low',
    costMultiplier: 0.85,
    llcFilingFee: '$110',
    llcFilingTimeDays: '1–3 business days online',
    salesTaxRate: '6.0% state + 0–3% local (range 6.0–9.0%)',
    needsStateBusinessLicense: false,
    needsAutomotiveRepairLicense: false,
    epaWasteTireProgram: true,
    epaProgramName: 'SCDHEC Waste Tire Program',
    epaTireDisposalFee: '$2 per new tire sold (state)',
    startupCostRange: {
      mobile: '$30K–$72K',
      singleBay: '$81K–$187K',
      multiBay: '$170K–$357K',
    },
    marketNotes:
      'South Carolina has been one of the strongest growth markets in the Southeast — BMW Spartanburg, Volvo Charleston, Boeing Charleston, and Port of Charleston combine to make this a manufacturing and logistics fleet hub. Greenville–Spartanburg has been growing fast. Low entry costs and quick LLC turnaround.',
    whyHere: [
      'BMW Spartanburg, Volvo, and Boeing Charleston drive industrial vehicle and supplier-fleet demand.',
      'Port of Charleston ranks among the top East Coast ports — trucking and intermodal demand is high.',
      'Greenville–Spartanburg is one of the fastest-growing metros in the Southeast.',
    ],
    watchouts: [
      'Hurricane exposure on the coast (Charleston, Myrtle Beach) drives commercial property insurance premiums.',
      'Hot, humid summers shorten tire life and inventory storage life.',
      'Local sales tax stacking can push combined rate to 9% in tourism counties.',
    ],
    sosUrl: 'https://sos.sc.gov/business-filings',
    taxUrl: 'https://dor.sc.gov/tax/sales',
    epaUrl: 'https://scdhec.gov/environment/your-land/scrap-tires',
  },

  'south-dakota': {
    slug: 'south-dakota',
    abbr: 'SD',
    name: 'South Dakota',
    capital: 'Pierre',
    registeredVehicles: '1.1M',
    topMetros: ['Sioux Falls', 'Rapid City', 'Aberdeen', 'Brookings'],
    costTier: 'low',
    costMultiplier: 0.85,
    llcFilingFee: '$150 (online) / $165 (paper)',
    llcFilingTimeDays: '1–3 business days online',
    salesTaxRate: '4.2% state + 0–2% local (range 4.2–6.2%)',
    needsStateBusinessLicense: false,
    needsAutomotiveRepairLicense: false,
    epaWasteTireProgram: true,
    epaProgramName: 'SD DANR Waste Tire Program',
    epaTireDisposalFee: 'Set by retailer; no fixed state per-tire fee',
    startupCostRange: {
      mobile: '$30K–$72K',
      singleBay: '$81K–$187K',
      multiBay: '$170K–$357K',
    },
    marketNotes:
      'South Dakota has no state income tax and one of the lowest state sales tax rates in the country (4.2%). Sioux Falls is a major regional financial center (Citibank, Wells Fargo back-office) and the dominant metro. Rapid City anchors the western half. Universal winter tire demand and a truck-heavy vehicle mix.',
    whyHere: [
      'No state income tax and one of the lowest state sales tax rates (4.2%).',
      'Sioux Falls financial-services concentration drives strong household incomes and corporate fleet demand.',
      'Truck/SUV-heavy vehicle mix supports higher-revenue LT tire sales.',
    ],
    watchouts: [
      'Small overall market — focus on Sioux Falls and Rapid City.',
      'Winter logistics and inventory lead times are challenging in the western half.',
      'Rural labor pools are thin; recruit early.',
    ],
    sosUrl: 'https://sosenterprise.sd.gov/BusinessServices/',
    taxUrl: 'https://dor.sd.gov/businesses/taxes/sales-use-tax/',
    epaUrl: 'https://danr.sd.gov/OfficeOfConservation/WasteManagement/wastetires.aspx',
  },
  tennessee: {
    slug: 'tennessee',
    abbr: 'TN',
    name: 'Tennessee',
    capital: 'Nashville',
    registeredVehicles: '5.8M',
    topMetros: ['Nashville', 'Memphis', 'Knoxville', 'Chattanooga', 'Clarksville'],
    costTier: 'low',
    costMultiplier: 0.85,
    llcFilingFee: '$300 ($50 per member, $300 min / $3,000 max) + $300 annual report',
    llcFilingTimeDays: '3–5 business days online',
    salesTaxRate: '7.0% state + 1.5–2.75% local (range 8.5–9.75%)',
    needsStateBusinessLicense: false,
    needsAutomotiveRepairLicense: false,
    epaWasteTireProgram: true,
    epaProgramName: 'TDEC Waste Tire Program',
    epaTireDisposalFee: '$1.35 per new tire sold (state pre-disposal fee)',
    startupCostRange: {
      mobile: '$30K–$72K',
      singleBay: '$81K–$187K',
      multiBay: '$170K–$357K',
    },
    marketNotes:
      'Tennessee has no state income tax on wages, and Nashville has been one of the fastest-growing metros in the country. Memphis is a major FedEx hub (FedEx Express World Hub) and one of the most logistics-heavy cities in the U.S. Combined sales tax is among the highest in the country (9.25–9.75% in most metros).',
    whyHere: [
      'No state income tax on wages preserves owner take-home.',
      'Memphis FedEx Express World Hub drives massive logistics fleet demand.',
      'Nashville is one of the fastest-growing metros in the U.S.',
    ],
    watchouts: [
      'Combined sales tax is among the highest in the country (often 9.25–9.75%); pricing transparency matters.',
      '$300 annual report fee is mandatory.',
      'LLC fee scales with members ($50 each, $300 min) — solo LLCs pay the floor.',
    ],
    sosUrl: 'https://sos.tn.gov/businesses',
    taxUrl: 'https://www.tn.gov/revenue/taxes/sales-and-use-tax.html',
    epaUrl: 'https://www.tn.gov/environment/program-areas/sw-mm-solid-waste-management/sw-mm-tire-environmental-fee.html',
  },
  utah: {
    slug: 'utah',
    abbr: 'UT',
    name: 'Utah',
    capital: 'Salt Lake City',
    registeredVehicles: '2.7M',
    topMetros: ['Salt Lake City', 'West Valley City', 'Provo', 'West Jordan', 'Orem'],
    costTier: 'mid',
    costMultiplier: 1.0,
    llcFilingFee: '$59',
    llcFilingTimeDays: '1–3 business days online',
    salesTaxRate: '4.85% state + 1.25–4% local (range 6.1–8.85%)',
    needsStateBusinessLicense: false,
    needsAutomotiveRepairLicense: true,
    automotiveRepairAgency: 'Utah State Tax Commission — Motor Vehicle Enforcement Division (New Tire Retailer Registration)',
    epaWasteTireProgram: true,
    epaProgramName: 'Utah DEQ Waste Tire Recycling Program',
    epaTireDisposalFee: '$1 per new tire sold (state recycling fee)',
    startupCostRange: {
      mobile: '$35K–$85K',
      singleBay: '$95K–$220K',
      multiBay: '$200K–$420K',
    },
    marketNotes:
      'Utah has been one of the fastest-growing states by population and registered vehicles for the past decade. The Wasatch Front (SLC, Provo, Ogden corridor) accounts for most of the demand. New tire retailers must register with the Motor Vehicle Enforcement Division and collect the state recycling fee.',
    whyHere: [
      'Among the fastest-growing states by population — vehicle base expanding 2–3% per year.',
      '$59 LLC filing fee and 1–3 day turnaround are among the fastest and cheapest in the U.S.',
      'Mountain traction demand drives winter and all-season tire sales.',
    ],
    watchouts: [
      'New Tire Retailer Registration with Motor Vehicle Enforcement Division is required — verify before opening.',
      'Wasatch Front commercial rents have risen 30%+ since 2020.',
      'Mountain shops face significant winter logistics and operating costs.',
    ],
    sosUrl: 'https://corporations.utah.gov/',
    taxUrl: 'https://tax.utah.gov/sales',
    epaUrl: 'https://deq.utah.gov/waste-management-and-radiation-control/waste-tire-recycling-program',
    repairLicenseUrl: 'https://tax.utah.gov/mvb',
  },
  vermont: {
    slug: 'vermont',
    abbr: 'VT',
    name: 'Vermont',
    capital: 'Montpelier',
    registeredVehicles: '0.56M',
    topMetros: ['Burlington', 'South Burlington', 'Rutland', 'Essex', 'Colchester'],
    costTier: 'mid',
    costMultiplier: 1.0,
    llcFilingFee: '$125 + $35 annual report',
    llcFilingTimeDays: '1–3 business days online',
    salesTaxRate: '6.0% state + 1% local option (range 6.0–7.0%)',
    needsStateBusinessLicense: false,
    needsAutomotiveRepairLicense: false,
    epaWasteTireProgram: true,
    epaProgramName: 'Vermont DEC Waste Tire Program',
    epaTireDisposalFee: 'Set by retailer; no fixed state per-tire fee',
    startupCostRange: {
      mobile: '$35K–$85K',
      singleBay: '$95K–$220K',
      multiBay: '$200K–$420K',
    },
    marketNotes:
      'Vermont is the smallest tire market by population, but universal winter tire demand and an aging vehicle base support steady replacement work. Burlington dominates. Studded tires are legal Oct 15 – May 31 and widely used.',
    whyHere: [
      'Universal winter / studded tire demand creates a guaranteed seasonal spike.',
      'Aging vehicle fleet supports steady replacement and repair revenue.',
      'Low competition outside Burlington — single shops can dominate regional markets.',
    ],
    watchouts: [
      'Very small overall market — total registered vehicles under 600K.',
      'Winter is long and harsh; budget elevated equipment maintenance.',
      'Rural Vermont inventory logistics require longer lead times.',
    ],
    sosUrl: 'https://sos.vermont.gov/corporations/',
    taxUrl: 'https://tax.vermont.gov/business/sales-and-use-tax',
    epaUrl: 'https://dec.vermont.gov/waste-management/solid/materials-mgmt/tires',
  },
  virginia: {
    slug: 'virginia',
    abbr: 'VA',
    name: 'Virginia',
    capital: 'Richmond',
    registeredVehicles: '7.6M',
    topMetros: ['Virginia Beach', 'Norfolk', 'Chesapeake', 'Richmond', 'Arlington'],
    costTier: 'mid',
    costMultiplier: 1.0,
    llcFilingFee: '$100 + $50 annual registration',
    llcFilingTimeDays: '1–3 business days online',
    salesTaxRate: '5.3% state + 0.7–1.7% local (range 5.3–7.0%, Hampton Roads/NoVa 6.0%)',
    needsStateBusinessLicense: false,
    needsAutomotiveRepairLicense: false,
    epaWasteTireProgram: true,
    epaProgramName: 'Virginia DEQ Waste Tire Program',
    epaTireDisposalFee: '$0.50 per new tire sold (state) + $1 in Northern Virginia',
    startupCostRange: {
      mobile: '$35K–$85K',
      singleBay: '$95K–$220K',
      multiBay: '$200K–$420K',
    },
    marketNotes:
      'Virginia combines a Northern Virginia tech/federal-contractor base with a Hampton Roads military and port economy. Mandatory annual safety inspection drives consistent walk-in volume for certified shops. Virginia inspection station certification is a separate process (Virginia State Police) worth pursuing.',
    whyHere: [
      'Mandatory annual safety inspection drives steady walk-in traffic for certified inspection stations.',
      'Hampton Roads naval and port fleet base (Norfolk Naval Station, Port of Virginia) drives commercial demand.',
      'Northern Virginia household incomes (Arlington, Fairfax) support premium-tire demand.',
    ],
    watchouts: [
      'Virginia State Police inspection station certification is a separate licensing process; budget 60–90 days.',
      'Northern Virginia commercial rents are among the highest outside major coastal CBDs.',
      'Hurricane and nor\'easter exposure on the coast raise commercial property insurance.',
    ],
    sosUrl: 'https://www.scc.virginia.gov/pages/Virginia-Limited-Liability-Companies',
    taxUrl: 'https://www.tax.virginia.gov/retail-sales-and-use-tax',
    epaUrl: 'https://www.deq.virginia.gov/land/recycling-litter-prevention/waste-tire-program',
  },
  washington: {
    slug: 'washington',
    abbr: 'WA',
    name: 'Washington',
    capital: 'Olympia',
    registeredVehicles: '6.9M',
    topMetros: ['Seattle', 'Spokane', 'Tacoma', 'Vancouver', 'Bellevue'],
    costTier: 'high',
    costMultiplier: 1.25,
    llcFilingFee: '$200 (online) / $180 (paper) + $60 annual report + $90 state Business License',
    llcFilingTimeDays: '2–5 business days online',
    salesTaxRate: '6.5% state + 0.5–4% local (range 7.0–10.5%)',
    needsStateBusinessLicense: true,
    needsAutomotiveRepairLicense: false,
    epaWasteTireProgram: true,
    epaProgramName: 'Washington Ecology Waste Tire Program',
    epaTireDisposalFee: '$1 per new tire sold (state)',
    startupCostRange: {
      mobile: '$45K–$105K',
      singleBay: '$118K–$275K',
      multiBay: '$250K–$525K',
    },
    marketNotes:
      'Washington has no state income tax but a Business & Occupation (B&O) tax on gross receipts (~0.471% retailing rate) plus a unified state Business License. Seattle metro household incomes are among the highest in the country and support premium-tire demand. Studded tires are legal Nov 1 – Mar 31.',
    whyHere: [
      'No state income tax preserves owner take-home.',
      'Seattle tech-sector incomes (Amazon, Microsoft, Boeing) drive premium-tire demand.',
      'Mountain pass traction laws and studded tire season drive winter demand.',
    ],
    watchouts: [
      'Business & Occupation (B&O) tax applies to gross receipts (~0.471% retailing) — owed regardless of profit.',
      'Washington State Business License is required ($90 initial); renews annually.',
      'Seattle commercial real estate is expensive; secondary metros (Spokane, Tacoma, Vancouver) offer better economics.',
    ],
    sosUrl: 'https://www.sos.wa.gov/corporations-charities/business-services',
    taxUrl: 'https://dor.wa.gov/taxes-rates/retail-sales-tax',
    epaUrl: 'https://ecology.wa.gov/waste-toxics/solid-waste-materials-management/waste-tires',
  },
  'west-virginia': {
    slug: 'west-virginia',
    abbr: 'WV',
    name: 'West Virginia',
    capital: 'Charleston',
    registeredVehicles: '1.4M',
    topMetros: ['Charleston', 'Huntington', 'Morgantown', 'Parkersburg', 'Wheeling'],
    costTier: 'low',
    costMultiplier: 0.85,
    llcFilingFee: '$100 + $25 annual report',
    llcFilingTimeDays: '5–10 business days online',
    salesTaxRate: '6.0% state + 0–1% local (range 6.0–7.0%)',
    needsStateBusinessLicense: false,
    needsAutomotiveRepairLicense: false,
    epaWasteTireProgram: true,
    epaProgramName: 'WVDEP Waste Tire Program',
    epaTireDisposalFee: 'Set by retailer; no fixed state per-tire fee',
    startupCostRange: {
      mobile: '$30K–$72K',
      singleBay: '$81K–$187K',
      multiBay: '$170K–$357K',
    },
    marketNotes:
      'West Virginia is a low-cost entry market with a small but stable vehicle base. Mountainous terrain shortens tire life through aggressive wear, and winter / all-season demand is strong. Energy-sector commercial demand has shifted with natural gas growth.',
    whyHere: [
      'Low labor and rent costs across the state.',
      'Mountainous driving shortens tire life and supports replacement demand.',
      'Natural gas / Marcellus Shale activity supports commercial truck demand in the north.',
    ],
    watchouts: [
      'Small overall market with declining population in some counties.',
      'Mountain roads, salt, and ice shorten equipment life significantly.',
      'Inventory logistics in rural counties require longer lead times.',
    ],
    sosUrl: 'https://sos.wv.gov/business/Pages/default.aspx',
    taxUrl: 'https://tax.wv.gov/Business/SalesAndUseTax/Pages/default.aspx',
    epaUrl: 'https://dep.wv.gov/dlr/oer/recycling/Pages/default.aspx',
  },
  wisconsin: {
    slug: 'wisconsin',
    abbr: 'WI',
    name: 'Wisconsin',
    capital: 'Madison',
    registeredVehicles: '5.2M',
    topMetros: ['Milwaukee', 'Madison', 'Green Bay', 'Kenosha', 'Racine'],
    costTier: 'mid',
    costMultiplier: 1.0,
    llcFilingFee: '$130 (online) / $170 (paper) + $25 annual report',
    llcFilingTimeDays: '5–7 business days online',
    salesTaxRate: '5.0% state + 0–0.6% local (range 5.0–5.6%, Milwaukee 5.5%)',
    needsStateBusinessLicense: false,
    needsAutomotiveRepairLicense: false,
    epaWasteTireProgram: true,
    epaProgramName: 'Wisconsin DNR Waste Tire Recycling Program',
    epaTireDisposalFee: 'Set by retailer; no fixed state per-tire fee',
    startupCostRange: {
      mobile: '$35K–$85K',
      singleBay: '$95K–$220K',
      multiBay: '$200K–$420K',
    },
    marketNotes:
      'Wisconsin has one of the lower combined sales tax rates in the Midwest (5.0–5.6%) and a strong manufacturing fleet base (Harley-Davidson, Kohler, Oshkosh Truck, Mercury Marine). Milwaukee and Madison anchor the market. Winter tire seasonal demand is strong.',
    whyHere: [
      'Among the lowest combined sales tax rates in the Midwest (5.0–5.6%).',
      'Manufacturing fleet base (Harley-Davidson, Oshkosh, Kohler) drives industrial vehicle demand.',
      'Madison and Milwaukee anchor the market with stable household incomes.',
    ],
    watchouts: [
      'Winter is long and severe; budget 15–20% higher equipment maintenance.',
      'Annual report fee ($25) is low but mandatory.',
      'Milwaukee commercial real estate is rising; Madison growth has compressed cap rates.',
    ],
    sosUrl: 'https://www.wdfi.org/corporations/',
    taxUrl: 'https://www.revenue.wi.gov/Pages/FAQS/pcs-sales.aspx',
    epaUrl: 'https://dnr.wisconsin.gov/topic/Recycling/Tires.html',
  },
  wyoming: {
    slug: 'wyoming',
    abbr: 'WY',
    name: 'Wyoming',
    capital: 'Cheyenne',
    registeredVehicles: '0.78M',
    topMetros: ['Cheyenne', 'Casper', 'Laramie', 'Gillette', 'Rock Springs'],
    costTier: 'low',
    costMultiplier: 0.85,
    llcFilingFee: '$100 + $60 annual report',
    llcFilingTimeDays: '1–3 business days online',
    salesTaxRate: '4.0% state + 0–2% local (range 4.0–6.0%)',
    needsStateBusinessLicense: false,
    needsAutomotiveRepairLicense: false,
    epaWasteTireProgram: false,
    startupCostRange: {
      mobile: '$30K–$72K',
      singleBay: '$81K–$187K',
      multiBay: '$170K–$357K',
    },
    marketNotes:
      'Wyoming has the smallest population of any state but a vehicle base disproportionately weighted toward trucks, SUVs, and commercial energy-sector fleets (oil, gas, coal, wind). No state income tax. Inventory logistics are challenging; lead times of 2–4 weeks are normal.',
    whyHere: [
      'No state income tax preserves owner take-home.',
      'Truck/SUV and energy-sector commercial fleet mix supports higher-revenue LT tire sales.',
      '$100 LLC filing and low ongoing fees — favorable formation economics.',
    ],
    watchouts: [
      'Very small overall market — vehicle base under 800K.',
      'Inventory logistics are challenging; lead times of 2–4 weeks and freight markups are normal.',
      'Winter is long and severe; mountain pass weather affects service-vehicle deployment.',
    ],
    sosUrl: 'https://sos.wyo.gov/Business/',
    taxUrl: 'https://revenue.wyo.gov/divisions/excise-tax-division',
  },
};

export const STATE_SLUGS = Object.keys(STATE_DATA);
